name: env_ufsreplay

dependencies:
  - conda-forge::python=3.8.5
  - conda-forge::netcdf4
  - conda-forge::f90nml
  - conda-forge::xarray
  - conda-forge::numpy
  - conda-forge::shapely
  - conda-forge::xesmf
