name: env_ufsreplay

dependencies:
  - conda-forge::python=3.7
  - conda-forge::netcdf4
  - conda-forge::f90nml
  - conda-forge::xarray
  - conda-forge::numpy
  - conda-forge::shapely
  - conda-forge::xesmf
variables:
  SCM_ROOT: $PWD/