gmtb_scm_time_integration
Contains subroutines to handle the SCM time stepping.
subroutine gmtb_scm_time_integration::filter (c_filter, temp_tracer, temp_T, temp_u, temp_v, state_tracer, state_T, state_u, state_v)
This subroutine performs the Robert-Asselin time filtering of the state variables.
subroutine gmtb_scm_time_integration::do_time_step (n_levels, n_columns, time_scheme, state_fldin, state_fldout, sfc_prop, diags, intrfc_fld, cld_prop, rad_tend, mdl_parm, tbddata, dyn_parm, state_tracer, state_T, state_u, state_v, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, u_force_tend, v_force_tend, T_force_tend, qv_force_tend, exner_l, phii, pres_l, lat, dt, lsswr, lslwr, thermo_forcing_type, mom_forcing_type, relax_time)
This subroutine calls nuopc_rad_update and nuopc_rad_run in nuopc_physics.F90 (if necessary) and apply_forcing_leapfrog from gmtb_scm_forcing and nuopc_phys_run, also from nuopc_physics.F90. The subroutine nuopc_rad_update calculates the time-dependent parameters required to run radiation, and nuopc_rad_run calculates the radiative heating rate (but does not apply it). The subroutine apply_forcing_leapfrog advances the state variables forward using the leapfrog method and nuopc_phys_run further changes the state variables using the forward method. By the end of this subroutine, the unfiltered state variables will have been stepped forward in time.
Detailed Description
Contains subroutines to handle the SCM time stepping.
Function/Subroutine Documentation
[do_time_step(n_levels, n_columns, time_scheme, state_fldin, state_fldout, sfc_prop, diags, intrfc_fld, cld_prop, rad_tend, mdl_parm, tbddata, dyn_parm, state_tracer, state_T, state_u, state_v, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, u_force_tend, v_force_tend, T_force_tend, qv_force_tend, exner_l, phii, pres_l, lat, dt, lsswr, lslwr, thermo_forcing_type, mom_forcing_type, relax_time)]subroutine gmtb_scm_time_integration::do_time_step (integer, intent(in) n_levels, integer, intent(in) n_columns, integer, intent(in) time_scheme, type(state_fields_in), intent(in) state_fldin, type(state_fields_out), intent(inout) state_fldout, type(sfc_properties), intent(in) sfc_prop, type(diagnostics), intent(in) diags, type(interface_fields), intent(in) intrfc_fld, type(cloud_properties), intent(in) cld_prop, type(radiation_tendencies), intent(in) rad_tend, type(model_parameters), intent(in) mdl_parm, type(tbd_ddt), intent(in) tbddata, type(dynamic_parameters), intent(inout) dyn_parm, real(kind=dp), dimension(:,:,:,:), intent(inout) state_tracer, real(kind=dp), dimension(:,:,:), intent(inout) state_T, real(kind=dp), dimension(:,:,:), intent(inout) state_u, real(kind=dp), dimension(:,:,:), intent(inout) state_v, real(kind=dp), dimension(:,:), intent(in) w_ls, real(kind=dp), dimension(:,:), intent(in) omega, real(kind=dp), dimension(:,:), intent(in) u_g, real(kind=dp), dimension(:,:), intent(in) v_g, real(kind=dp), dimension(:,:), intent(in) u_nudge, real(kind=dp), dimension(:,:), intent(in) v_nudge, real(kind=dp), dimension(:,:), intent(in) T_nudge, real(kind=dp), dimension(:,:), intent(in) thil_nudge, real(kind=dp), dimension(:,:), intent(in) qt_nudge, real(kind=dp), dimension(:,:), intent(in) dT_dt_rad, real(kind=dp), dimension(:,:), intent(in) h_advec_thil, real(kind=dp), dimension(:,:), intent(in) h_advec_qt, real(kind=dp), dimension(:,:), intent(in) v_advec_thil, real(kind=dp), dimension(:,:), intent(in) v_advec_qt, real(kind=dp), dimension(:,:), intent(out) u_force_tend, real(kind=dp), dimension(:,:), intent(out) v_force_tend, real(kind=dp), dimension(:,:), intent(out) T_force_tend, real(kind=dp), dimension(:,:), intent(out) qv_force_tend, real(kind=dp), dimension(:,:), intent(in) exner_l, real(kind=dp), dimension(:,:), intent(in) phii, real(kind=dp), dimension(:,:), intent(in) pres_l, real(kind=dp), dimension(:), intent(in) lat, real(kind=dp), intent(in) dt, logical, intent(in) lsswr, logical, intent(in) lslwr, integer, intent(in) thermo_forcing_type, integer, intent(in) mom_forcing_type, real(kind=dp), intent(in) relax_time)
This subroutine calls nuopc_rad_update and nuopc_rad_run in nuopc_physics.F90 (if necessary) and apply_forcing_leapfrog from gmtb_scm_forcing and nuopc_phys_run, also from nuopc_physics.F90. The subroutine nuopc_rad_update calculates the time-dependent parameters required to run radiation, and nuopc_rad_run calculates the radiative heating rate (but does not apply it). The subroutine apply_forcing_leapfrog advances the state variables forward using the leapfrog method and nuopc_phys_run further changes the state variables using the forward method. By the end of this subroutine, the unfiltered state variables will have been stepped forward in time.
Parameters
in n_levels number of model levels
in n_columns number of model columns
in time_scheme time-stepping scheme choice (1=forward, 2=filtered leapfrog)
in mdl_parm NUOPC DDT containing model configuration parameters
in,out dyn_parm NUOPC DDT containing parameters that change throughout the integration often
in state_fldin NUOPC DDT containing the model state variables before the time step
in sfc_prop NUOPC DDT containing surface variables
in diags NUOPC DDT containing diagnostic variables
in cld_prop NUOPC DDT containing cloud property variables
in rad_tend NUOPC DDT containing radiaitve tendencies
in intrfc_fld NUOPC DDT containing interfacial variables
in,out state_fldout NUOPC DDT that are updated during the time step
in tbddata NUOPC DDT containing unclassified variables
in,out state_tracer model state tracers
in,out state_t model state temperature
in,out state_u model state zonal wind
in,out state_v model state meridional wind
in w_ls large scale w (m/s) (horizontal, vertical)
in omega large scale pressure velocity (Pa/s) (horizontal, vertical)
in u_g geostrophic zonal wind (m/s) (horizontal, vertical)
in v_g geostrophic meridional wind (m/s) (horizontal, vertical)
in u_nudge nudging zonal wind (m/s) (horizontal, vertical)
in v_nudge nudging meridional wind (m/s) (horizontal, vertical)
in t_nudge nudging absolute temperature (K) (horizontal, vertical)
in thil_nudge nudging liq. pot. temperatuer (K) (horizontal, vertical)
in qt_nudge nudging specific humidity (K) (horizontal, vertical)
in dt_dt_rad radiative heating rate (K/s) (horizontal, vertical)
in h_advec_thil change in theta_il due to horizontal advection (K/s) (horizontal, vertical)
in h_advec_qt change in q_t due to horizontal advection (kg/kg /s) (horizontal, vertical)
in v_advec_thil change in theta_il due to vertical advection (K/s) (horizontal, vertical)
in v_advec_qt change in q_t due to vertical advection (kg/kg /s) (horizontal, vertical)
in lat latitude in radians
in dt time step (s)
in exner_l exner function at model level centers (horizontal, vertical)
in phii geopotential at model level interfaces (horizontal, vertical)
in pres_l pressure at model level centers (horizontal, vertical)
in relax_time time scale for relaxation to observations (s)
in lsswr logical flag for calling shortwave radiation
in lslwr logical flag for calling longwave radiation
in thermo_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
in mom_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
out u_force_tend sum of all forcing for zonal momentum (horizontal, vertical)
out v_force_tend sum of all forcing for meridional momentum (horizontal, vertical)
out t_force_tend sum of all forcing for temperature (horizontal, vertical)
out qv_force_tend sum of all forcing for water vapor (horizontal, vertical)
Algorithm
Call nuopc_rad_update and nuopr_rad_run as necessary. State variables are not affected by these calls. Only radiative heating rates (and other rad. diagnostics) are returned.
Call apply_forcing_* from gmtb_scm_forcing. This routine updates the `input` state variables for the physics call. It effectively replaces the change of the state variables due to dynamics.
Call nuopc_phys_run to complete the forward time step. The unfiltered, updated state variables are in the NUOPC DDT state_fldout, which points to state_var(:,:,2).
Definition at line 54 of file gmtb_scm_time_integration.f90.
References gmtb_scm_forcing::apply_forcing_forward_euler(), and gmtb_scm_forcing::apply_forcing_leapfrog().
Referenced by gmtb_scm_main::gmtb_scm_main_sub().
subroutine gmtb_scm_time_integration::filter (real(kind=dp), intent(in) c_filter, real(kind=dp), dimension(:,:,:,:), intent(in) temp_tracer, real(kind=dp), dimension(:,:,:), intent(in) temp_T, real(kind=dp), dimension(:,:,:), intent(in) temp_u, real(kind=dp), dimension(:,:,:), intent(in) temp_v, real(kind=dp), dimension(:,:,:,:), intent(inout) state_tracer, real(kind=dp), dimension(:,:,:), intent(inout) state_T, real(kind=dp), dimension(:,:,:), intent(inout) state_u, real(kind=dp), dimension(:,:,:), intent(inout) state_v)
This subroutine performs the Robert-Asselin time filtering of the state variables.
Parameters
in c_filter filter constant (equal to 1 - the constant used in the GFS)
in temp_tracer temporary copy of the state tracer variables before the latest forcing/physics update (horizontal, vertical, tracer_index, iteration)
in temp_t temporary copy of the state temperature before the latest forcing/physics update (horizontal, vertical, iteration)
in temp_u temporary copy of the state zonal wind before the latest forcing/physics update (horizontal, vertical, iteration)
in temp_v temporary copy of the state meridional wind before the latest forcing/physics update (horizontal, vertical, iteration)
in,out state_tracer state tracer variables containing the section of the array to be updated and the section that contains the latest unfiltered values (horizontal, vertical, tracer_index, iteration)
in,out state_t state temperature containing the section of the array to be updated and the section that contains the latest unfiltered values (horizontal, vertical, iteration)
in,out state_u state zonal wind containing the section of the array to be updated and the section that contains the latest unfiltered values (horizontal, vertical, iteration)
in,out state_v state merdional wind containing the section of the array to be updated and the section that contains the latest unfiltered values (horizontal, vertical, iteration)
Algorithm
The filtered state variables are calculated using
 \overline{x^\tau}=(1-c)x^\tau + 0.5c\left(x^{\tau +1} + \overline{x^{\tau - 1}}\right) 
 where $\overline{x^\tau}$ is the filtered value of variable $x$ at the current iteration, $x^\tau$ is the unfiltered value of the previous time step, $x^{\tau +1}$ is the unfiltered value that was just updated by the forcing and physics, and $\overline{x^{\tau - 1}}$ is the filtered value of the variable from the previous iteration, and $c$ is the filtering constant.
Definition at line 22 of file gmtb_scm_time_integration.f90.
Referenced by gmtb_scm_main::gmtb_scm_main_sub().