gmtb_scm_input
Contains input-related subroutines -- reading in model configuration from file or the command line and reading in the case initial conditions and forcing; also contains reference profile input (temporarily hard-coded).
Functions/Subroutines
subroutine gmtb_scm_input::get_reference_profile (nlev, pres, T, qv, ozone)
Subroutine to get reference profile to use above the case data (temporarily hard-coded profile)
subroutine gmtb_scm_input::get_reference_profile_old (nlev, pres, T, qv, ozone)
Subroutine to get reference profile to use above the case data (temporarily hard-coded profile)
subroutine gmtb_scm_input::check (status)
Generic subroutine to check for netCDF I/O errors.
subroutine gmtb_scm_input::get_config_nml (experiment_name, model_name, physics_suite, case_name, dt, time_scheme, runtime, output_frequency, swrad_frequency, lwrad_frequency, n_levels, output_dir, output_file, thermo_forcing_type, mom_forcing_type, relax_time)
Subroutine to get basic model configuration data from a namelist file (whose name is specified as the first argument on the command line) and from data entered on the command line with the format: `var1='string' var2=d.d var3=i`. Namelist variables listed on the command line override those that are specified in the external namelist file. The case configuration namelist variables are also written out to a namelist file placed in the output directory. Note: This routine uses GET_COMMAND which is an intrinsic routine in the Fortran 2003 standard. This requires that the compiler supports this standard.
subroutine gmtb_scm_input::get_case_init (case_name, input_nlev, input_ntimes, input_pres, input_time, input_height, input_thetail, input_qt, input_ql, input_qi, input_u, input_v, input_tke, input_ozone, input_lat, input_lon, input_pres_surf, input_T_surf, input_w_ls, input_omega, input_u_g, input_v_g, input_u_nudge, input_v_nudge, input_T_nudge, input_thil_nudge, input_qt_nudge, input_dT_dt_rad, input_h_advec_thetail, input_h_advec_qt, input_v_advec_thetail, input_v_advec_qt)
Subroutine to read the netCDF file containing case initialization and forcing. The forcing files (netCDF4) should be located in the `processed_case_input` directory.
Detailed Description
Contains input-related subroutines -- reading in model configuration from file or the command line and reading in the case initial conditions and forcing; also contains reference profile input (temporarily hard-coded).
Function/Subroutine Documentation
subroutine gmtb_scm_input::check (integer, intent(in) status)
Generic subroutine to check for netCDF I/O errors.
Definition at line 392 of file gmtb_scm_input.f90.
Referenced by gmtb_scm_input::get_case_init(), gmtb_scm_output::output_append(), and gmtb_scm_output::output_init().
[get_case_init(case_name, input_nlev, input_ntimes, input_pres, input_time, input_height, input_thetail, input_qt, input_ql, input_qi, input_u, input_v, input_tke, input_ozone, input_lat, input_lon, input_pres_surf, input_T_surf, input_w_ls, input_omega, input_u_g, input_v_g, input_u_nudge, input_v_nudge, input_T_nudge, input_thil_nudge, input_qt_nudge, input_dT_dt_rad, input_h_advec_thetail, input_h_advec_qt, input_v_advec_thetail, input_v_advec_qt)]subroutine gmtb_scm_input::get_case_init (character(len=*), intent(in) case_name, integer, intent(out) input_nlev, integer, intent(out) input_ntimes, real(kind=dp), dimension(:), intent(out), allocatable input_pres, real(kind=dp), dimension(:), intent(out), allocatable input_time, real(kind=dp), dimension(:), intent(out), allocatable input_height, real(kind=dp), dimension(:), intent(out), allocatable input_thetail, real(kind=dp), dimension(:), intent(out), allocatable input_qt, real(kind=dp), dimension(:), intent(out), allocatable input_ql, real(kind=dp), dimension(:), intent(out), allocatable input_qi, real(kind=dp), dimension(:), intent(out), allocatable input_u, real(kind=dp), dimension(:), intent(out), allocatable input_v, real(kind=dp), dimension(:), intent(out), allocatable input_tke, real(kind=dp), dimension(:), intent(out), allocatable input_ozone, real(kind=dp), dimension(:), intent(out), allocatable input_lat, real(kind=dp), dimension(:), intent(out), allocatable input_lon, real(kind=dp), dimension(:), intent(out), allocatable input_pres_surf, real(kind=dp), dimension(:), intent(out), allocatable input_T_surf, real(kind=dp), dimension(:,:), intent(out), allocatable input_w_ls, real(kind=dp), dimension(:,:), intent(out), allocatable input_omega, real(kind=dp), dimension(:,:), intent(out), allocatable input_u_g, real(kind=dp), dimension(:,:), intent(out), allocatable input_v_g, real(kind=dp), dimension(:,:), intent(out), allocatable input_u_nudge, real(kind=dp), dimension(:,:), intent(out), allocatable input_v_nudge, real(kind=dp), dimension(:,:), intent(out), allocatable input_T_nudge, real(kind=dp), dimension(:,:), intent(out), allocatable input_thil_nudge, real(kind=dp), dimension(:,:), intent(out), allocatable input_qt_nudge, real(kind=dp), dimension(:,:), intent(out), allocatable input_dT_dt_rad, real(kind=dp), dimension(:,:), intent(out), allocatable input_h_advec_thetail, real(kind=dp), dimension(:,:), intent(out), allocatable input_h_advec_qt, real(kind=dp), dimension(:,:), intent(out), allocatable input_v_advec_thetail, real(kind=dp), dimension(:,:), intent(out), allocatable input_v_advec_qt)
Subroutine to read the netCDF file containing case initialization and forcing. The forcing files (netCDF4) should be located in the `processed_case_input` directory.
Parameters
in case_name this routine expects to find `case_name.nc` in the processed_case_input dir
out input_nlev number of levels in the input file
out input_ntimes number of times represented in the input file
out input_pres input file pressure levels (Pa)
out input_time input file times (seconds since the beginning of the case)
out input_height height of the pressure levels
out input_thetail ice-liquid water potential temperature profile (K)
out input_qt total water specific humidity profile (kg kg^-1)
out input_ql liquid water specific humidity profile (kg kg^-1)
out input_qi ice water specific humidity profile (kg kg^-1)
out input_u east-west horizontal wind profile (m s^-1)
out input_v north-south horizontal wind profile (m s^-1)
out input_tke TKE profile (m^2 s^-2)
out input_ozone ozone profile (kg kg^-1)
out input_lat time-series of column latitude
out input_lon time-series of column longitude
out input_pres_surf time-series of surface pressure (Pa)
out input_t_surf time-series of surface temperature (K)
out input_w_ls 2D vertical velocity (m s^-1)
out input_omega 2D pressure vertical velocity (Pa s^-1)
out input_u_g 2D geostrophic east-west wind (m s^-1)
out input_v_g 2D geostrophic north-south wind (m s^-1)
out input_u_nudge 2D nudging east-west wind (m s^-1)
out input_v_nudge 2D nudging north-south wind (m s^-1)
out input_t_nudge 2D nudging abs. temperature (K)
out input_thil_nudge 2D nudging liq. pot. temperature (K)
out input_qt_nudge 2D nudging specific humidity (kg kg^-1)
out input_dt_dt_rad 2D radiative heating rate (K s^-1)
out input_h_advec_thetail 2D theta_il tendency due to large-scale horizontal advection (K s^-1)
out input_h_advec_qt 2D q_t tendency due to large-scale horizontal advection (kg kg^-1 s^-1)
out input_v_advec_thetail 2D theta_il tendency due to large-scale vertical advection (K s^-1)
out input_v_advec_qt 2D q_t tendency due to large-scale horizontal vertical (kg kg^-1 s^-1)
Algorithm
Open the case input file found in the processed_case_input dir corresponding to the experiment name.
Get the dimensions (global group).
Allocate the dimension variables.
Read in the dimension variables.
Read in the initial conditions.
Find group ncid for initial group.
Allocate the initial profiles.
Read in the initial profiles. The variable names in all input files are expected to be identical.
Read in the forcing data.
Find group ncid for forcing group.
(Recall that multidimensional arrays need to be read in with the order of dimensions reversed from the netCDF file).
Allocate the time-series and 2D forcing data.
Read in the time-series and 2D forcing data.
Definition at line 168 of file gmtb_scm_input.f90.
References gmtb_scm_input::check().
Referenced by gmtb_scm_main::gmtb_scm_main_sub().
subroutine gmtb_scm_input::get_config_nml (character(len=80), intent(out) experiment_name, character(len=80), intent(out) model_name, character(len=80), intent(out) physics_suite, character(len=80), intent(out) case_name, real(kind=dp), intent(out) dt, integer, intent(out) time_scheme, real(kind=dp), intent(out) runtime, real(kind=dp), intent(out) output_frequency, real(kind=dp), intent(out) swrad_frequency, real(kind=dp), intent(out) lwrad_frequency, integer, intent(out) n_levels, character(len=80), intent(out) output_dir, character(len=80), intent(out) output_file, integer, intent(out) thermo_forcing_type, integer, intent(out) mom_forcing_type, real(kind=dp), intent(out) relax_time)
Subroutine to get basic model configuration data from a namelist file (whose name is specified as the first argument on the command line) and from data entered on the command line with the format: `var1='string' var2=d.d var3=i`. Namelist variables listed on the command line override those that are specified in the external namelist file. The case configuration namelist variables are also written out to a namelist file placed in the output directory. Note: This routine uses GET_COMMAND which is an intrinsic routine in the Fortran 2003 standard. This requires that the compiler supports this standard.
Parameters
out experiment_name name of the experiment configuration file (usually case name)
out model_name name of the host model (currently only GFS supported)
out physics_suite name of the physics suite name (currently only GFS_operational supported)
out case_name name of case initialization and forcing dataset
out dt time step in seconds
out runtime total runtime in seconds
out output_frequency freqency of output writing in seconds
out swrad_frequency freqency of calling SW radiation in seconds
out lwrad_frequency freqency of calling SW radiation in seconds
out n_levels number of model levels (currently only 64 supported)
out time_scheme 1 => forward Euler, 2 => filtered leapfrog
out output_dir name of the output directory
out output_file name of the output file (without the file extension)
out thermo_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
out mom_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
out relax_time relaxation time scale (s)
Algorithm
Define default values for case configuration (to be overridden by external namelist file or command line arguments)
Parse the command line arguments.
Get the entire command used to invoke the SCM (including arguments)
Discard SCM invocation command.
Get experiment name from first argument (if not present, use default values in this source file)
Put remaining command line arguments into `internal` namelist to read in after the external file.
Attempt to read in external namelist file.
`Read` in internal namelist variables from command line.
Check for namelist reading errors. If errors are found, output the namelist variables that were loaded to console and ask user for input on whether to proceed.
If there was an error reading from the command line, use the default values of the namelist variables and check with the user whether to continue.
Write the case_config namelist variables to an output file in the output directory for inspection or re-use.
Definition at line 28 of file gmtb_scm_input.f90.
Referenced by gmtb_scm_main::gmtb_scm_main_sub().
subroutine gmtb_scm_input::get_reference_profile (integer, intent(out) nlev, real(kind=dp), dimension(:), intent(out), allocatable pres, real(kind=dp), dimension(:), intent(out), allocatable T, real(kind=dp), dimension(:), intent(out), allocatable qv, real(kind=dp), dimension(:), intent(out), allocatable ozone)
Subroutine to get reference profile to use above the case data (temporarily hard-coded profile)
Parameters
out nlev number of pressure levels in the reference profile
out pres reference profile pressure (Pa)
out t reference profile temperature (K)
out qv reference profile specific humidity (kg kg^-1)
out ozone reference profile ozone concentration (kg kg^-1)
Definition at line 323 of file gmtb_scm_input.f90.
Referenced by gmtb_scm_main::gmtb_scm_main_sub().
subroutine gmtb_scm_input::get_reference_profile_old (integer, intent(out) nlev, real(kind=dp), dimension(:), intent(out), allocatable pres, real(kind=dp), dimension(:), intent(out), allocatable T, real(kind=dp), dimension(:), intent(out), allocatable qv, real(kind=dp), dimension(:), intent(out), allocatable ozone)
Subroutine to get reference profile to use above the case data (temporarily hard-coded profile)
Parameters
out nlev number of pressure levels in the reference profile
out pres reference profile pressure (Pa)
out t reference profile temperature (K)
out qv reference profile specific humidity (kg kg^-1)
out ozone reference profile ozone concentration (kg kg^-1)
Todo
Todo write a more sophisticated reference profile subroutine (can choose between reference profiles)
For the prototype, the 'McClatchey' sounding used in Jennifer Fletcher's code is hardcoded.
Definition at line 362 of file gmtb_scm_input.f90.