gmtb_scm_output
Contains output-related subroutines.
subroutine gmtb_scm_output::output_init (output_dir, output_file, n_columns, n_levels, year, month, day, hour)
This subroutine initializes the output netCDF file, `output.nc`, placed in the directory specified by the case_config file used.
subroutine gmtb_scm_output::output_append (output_dir, output_file, record_number, time, pres_l, pres_i, sigma_l, sigma_i, phi_l, phi_i, qv, T, u, v, qc, u_force_tend, v_force_tend, T_force_tend, qv_force_tend, w_ls, u_g, v_g, dT_dt_rad_forc, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, T_s, pres_s, lhf, shf, tau_u, tau_v, cldcov, swh, hlw, tprcp, rain, rainc, pwat, dT_dt_lwrad, dT_dt_swrad, dT_dt_PBL, dT_dt_deepconv, dT_dt_shalconv, dT_dt_micro, dq_dt_PBL, dq_dt_deepconv, dq_dt_shalconv, dq_dt_micro, upd_mf, dwn_mf, det_mf, hpbl, sw_up_TOA_tot, sw_dn_TOA_tot, sw_up_TOA_clr, sw_up_sfc_tot, sw_dn_sfc_tot, sw_up_sfc_clr, sw_dn_sfc_clr, lw_up_TOA_tot, lw_up_TOA_clr, lw_up_sfc_tot, lw_up_sfc_clr, lw_dn_sfc_tot, lw_dn_sfc_clr)
This subroutine appends data to the `output.nc` file.
Detailed Description
Contains output-related subroutines.
Function/Subroutine Documentation
[output_append(output_dir, output_file, record_number, time, pres_l, pres_i, sigma_l, sigma_i, phi_l, phi_i, qv, T, u, v, qc, u_force_tend, v_force_tend, T_force_tend, qv_force_tend, w_ls, u_g, v_g, dT_dt_rad_forc, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, T_s, pres_s, lhf, shf, tau_u, tau_v, cldcov, swh, hlw, tprcp, rain, rainc, pwat, dT_dt_lwrad, dT_dt_swrad, dT_dt_PBL, dT_dt_deepconv, dT_dt_shalconv, dT_dt_micro, dq_dt_PBL, dq_dt_deepconv, dq_dt_shalconv, dq_dt_micro, upd_mf, dwn_mf, det_mf, hpbl, sw_up_TOA_tot, sw_dn_TOA_tot, sw_up_TOA_clr, sw_up_sfc_tot, sw_dn_sfc_tot, sw_up_sfc_clr, sw_dn_sfc_clr, lw_up_TOA_tot, lw_up_TOA_clr, lw_up_sfc_tot, lw_up_sfc_clr, lw_dn_sfc_tot, lw_dn_sfc_clr)]subroutine gmtb_scm_output::output_append (character(len=*), intent(in) output_dir, character(len=*), intent(in) output_file, integer, intent(in) record_number, real(kind=dp), intent(in) time, real(kind=dp), dimension(:,:), intent(in) pres_l, real(kind=dp), dimension(:,:), intent(in) pres_i, real(kind=dp), dimension(:,:), intent(in) sigma_l, real(kind=dp), dimension(:,:), intent(in) sigma_i, real(kind=dp), dimension(:,:), intent(in) phi_l, real(kind=dp), dimension(:,:), intent(in) phi_i, real(kind=dp), dimension(:,:), intent(in) qv, real(kind=dp), dimension(:,:), intent(in) T, real(kind=dp), dimension(:,:), intent(in) u, real(kind=dp), dimension(:,:), intent(in) v, real(kind=dp), dimension(:,:), intent(in) qc, real(kind=dp), dimension(:,:), intent(in) u_force_tend, real(kind=dp), dimension(:,:), intent(in) v_force_tend, real(kind=dp), dimension(:,:), intent(in) T_force_tend, real(kind=dp), dimension(:,:), intent(in) qv_force_tend, real(kind=dp), dimension(:,:), intent(in) w_ls, real(kind=dp), dimension(:,:), intent(in) u_g, real(kind=dp), dimension(:,:), intent(in) v_g, real(kind=dp), dimension(:,:), intent(in) dT_dt_rad_forc, real(kind=dp), dimension(:,:), intent(in) h_advec_thil, real(kind=dp), dimension(:,:), intent(in) h_advec_qt, real(kind=dp), dimension(:,:), intent(in) v_advec_thil, real(kind=dp), dimension(:,:), intent(in) v_advec_qt, real(kind=dp), dimension(:), intent(in) T_s, real(kind=dp), dimension(:), intent(in) pres_s, real(kind=dp), dimension(:), intent(in) lhf, real(kind=dp), dimension(:), intent(in) shf, real(kind=dp), dimension(:), intent(in) tau_u, real(kind=dp), dimension(:), intent(in) tau_v, real(kind=dp), dimension(:,:), intent(in) cldcov, real(kind=dp), dimension(:,:), intent(in) swh, real(kind=dp), dimension(:,:), intent(in) hlw, real(kind=dp), dimension(:), intent(in) tprcp, real(kind=dp), dimension(:), intent(in) rain, real(kind=dp), dimension(:), intent(in) rainc, real(kind=dp), dimension(:), intent(in) pwat, real(kind=dp), dimension(:,:), intent(in) dT_dt_lwrad, real(kind=dp), dimension(:,:), intent(in) dT_dt_swrad, real(kind=dp), dimension(:,:), intent(in) dT_dt_PBL, real(kind=dp), dimension(:,:), intent(in) dT_dt_deepconv, real(kind=dp), dimension(:,:), intent(in) dT_dt_shalconv, real(kind=dp), dimension(:,:), intent(in) dT_dt_micro, real(kind=dp), dimension(:,:), intent(in) dq_dt_PBL, real(kind=dp), dimension(:,:), intent(in) dq_dt_deepconv, real(kind=dp), dimension(:,:), intent(in) dq_dt_shalconv, real(kind=dp), dimension(:,:), intent(in) dq_dt_micro, real(kind=dp), dimension(:,:), intent(in) upd_mf, real(kind=dp), dimension(:,:), intent(in) dwn_mf, real(kind=dp), dimension(:,:), intent(in) det_mf, real(kind=dp), dimension(:), intent(in) hpbl, real(kind=dp), dimension(:), intent(in) sw_up_TOA_tot, real(kind=dp), dimension(:), intent(in) sw_dn_TOA_tot, real(kind=dp), dimension(:), intent(in) sw_up_TOA_clr, real(kind=dp), dimension(:), intent(in) sw_up_sfc_tot, real(kind=dp), dimension(:), intent(in) sw_dn_sfc_tot, real(kind=dp), dimension(:), intent(in) sw_up_sfc_clr, real(kind=dp), dimension(:), intent(in) sw_dn_sfc_clr, real(kind=dp), dimension(:), intent(in) lw_up_TOA_tot, real(kind=dp), dimension(:), intent(in) lw_up_TOA_clr, real(kind=dp), dimension(:), intent(in) lw_up_sfc_tot, real(kind=dp), dimension(:), intent(in) lw_up_sfc_clr, real(kind=dp), dimension(:), intent(in) lw_dn_sfc_tot, real(kind=dp), dimension(:), intent(in) lw_dn_sfc_clr)
This subroutine appends data to the `output.nc` file.
Parameters
in output_dir name of the output directory
in output_file name of the output file
in record_number the record counter
in time elapsed model time
in pres_l pressure on model layer centers (Pa) (horizontal, vertical)
in pres_i pressure on model layer interfaces (Pa) (horizontal, vertical)
in sigma_l sigma (p/p_s) on model layer centers (Pa) (horizontal, vertical)
in sigma_i sigma (p/p_s) on model layer interfaces (Pa) (horizontal, vertical)
in phi_l geopotential on model layer centers (Pa) (horizontal, vertical)
in phi_i geopotential on model layer interfaces (Pa) (horizontal, vertical)
in qv water vapor specific humidity on model layer centers (kg/kg) (horizontal, vertical)
in t absolute temperature on model layer centers (K) (horizontal, vertical)
in u zonal wind on model layer centers (m/s) (horizontal, vertical)
in v meridional wind on model layer centers (m/s) (horizontal, vertical)
in qc suspended cloud water on model layer centers (kg/kg) (horizontal, vertical)
in u_force_tend total forcing tendency for zonal momentum (m/s /s) (horizontal, vertical)
in v_force_tend total forcing tendency for meridional momentum (m/s /s) (horizontal, vertical)
in t_force_tend total forcing tendency for absolute temperature (K /s) (horizontal, vertical)
in qv_force_tend total forcing tendency for water vapor specific humidity (kg/kg /s) (horizontal, vertical)
in w_ls large-scale vertical velocity (m/s) (horizontal, vertical)
in u_g geostrophic zonal wind (m/s) (horizontal, vertical)
in v_g geostrophic meridional wind (m/s) (horizontal, vertical)
in dt_dt_rad_forc prescribed radiative heating rate (K/s) (horizontal, vertical)
in h_advec_thil large-scale horizontal advective heating rate (K/s) (horizontal, vertical)
in h_advec_qt large-scale horizontal advective moistening rate (kg/kg /s) (horizontal, vertical)
in v_advec_thil large-scale vertical advective heating rate (K/s) (horizontal, vertical)
in v_advec_qt large-scale vertical advective moistening rate (kg/kg /s) (horizontal, vertical)
in cldcov cloud fraction (horizontal, vertical)
in t_s surface temperature (K) (hoizontal)
in pres_s surface pressure (Pa) (horizontal)
in lhf surface latent heat flux (W/m^2) (horizontal)
in shf surface sensible heat flux (W/m^2) (horizontal)
in tau_u surface zonal wind stress (horizontal)
in tau_v surface meridional wind stress (horizontal)
in swh calculated SW radiative heating rate (K/s) (horizontal, vertical)
in hlw calculated LW radiative heating rate (K/s) (horizontal, vertical)
in tprcp surface precipitation (horizontal)
in rain surface total rain (m/s) (horizontal)
in rainc surface convective rain (m/s) (horizontal)
in pwat surface rain (horizontal)
in dt_dt_lwrad change in temperature due to lw rad scheme (K/s) (horizontal, vertical)
in dt_dt_swrad change in temperature due to sw rad scheme (K/s) (horizontal, vertical)
in dt_dt_pbl change in temperature due to PBL scheme (K/s) (horizontal, vertical)
in dt_dt_deepconv change in temperature due to deep conv scheme (K/s) (horizontal, vertical)
in dt_dt_shalconv change in temperature due to shal conv scheme (K/s) (horizontal, vertical)
in dt_dt_micro change in temperature due to micro scheme (K/s) (horizontal, vertical)
in dq_dt_pbl change in moisture due to PBL scheme (kg/kg/s) (horizontal, vertical)
in dq_dt_deepconv change in moisture due to deep conv scheme (kg/kg/s) (horizontal, vertical)
in dq_dt_shalconv change in moisture due to shal conv scheme (kg/kg/s) (horizontal, vertical)
in dq_dt_micro change in moisture due to micro scheme (kg/kg/s) (horizontal, vertical)
in upd_mf updraft mass flux (kg m^-2 s^-1) (horizontal, vertical)
in dwn_mf downdraft mass flux (kg m^-2 s^-1) (horizontal, vertical)
in det_mf detrainment mass flux (kg m^-2 s^-1) (horizontal, vertical)
in hpbl PBL height (m) (horizontal)
in sw_up_toa_tot total sky upward sw flux at toa ($W/m^2$) (horizontal)
in sw_dn_toa_tot total sky downward sw flux at toa ($W/m^2$) (horizontal)
in sw_up_toa_clr clear sky upward sw flux at toa ($W/m^2$) (horizontal)
in sw_up_sfc_tot total sky upward sw flux at sfc ($W/m^2$) (horizontal)
in sw_dn_sfc_tot total sky downward sw flux at sfc ($W/m^2$) (horizontal)
in sw_up_sfc_clr clear sky upward sw flux at sfc ($W/m^2$) (horizontal)
in sw_dn_sfc_clr clear sky downward sw flux at sfc ($W/m^2$) (horizontal)
in lw_up_toa_tot total sky upward LW flux at toa ($W/m^2$) (horizontal)
in lw_up_toa_clr clear sky upward LW flux at toa ($W/m^2$) (horizontal)
in lw_up_sfc_tot total sky upward LW flux at sfc ($W/m^2$) (horizontal)
in lw_up_sfc_clr clear sky upward LW flux at sfc ($W/m^2$) (horizontal)
in lw_dn_sfc_tot total sky downward LW flux at sfc ($W/m^2$) (horizontal)
in lw_dn_sfc_clr clear sky downward LW flux at sfc ($W/m^2$) (horizontal)
Algorithm
Open the file.
Append all of the variables to the file.
Close the file.
Definition at line 175 of file gmtb_scm_output.f90.
References gmtb_scm_input::check().
Referenced by gmtb_scm_main::gmtb_scm_main_sub().
subroutine gmtb_scm_output::output_init (character(len=*), intent(in) output_dir, character(len=*), intent(in) output_file, integer, intent(in) n_columns, integer, intent(in) n_levels, integer, intent(in) year, integer, intent(in) month, integer, intent(in) day, integer, intent(in) hour)
This subroutine initializes the output netCDF file, `output.nc`, placed in the directory specified by the case_config file used.
Parameters
in output_dir name of the output directory
in output_file name of the output file
in n_columns number of model columns
in n_levels number of model levels
in hour initial date
Algorithm
Create the output directory if necessary using a system call.
Create the output file in the output directory.
Define netCDF dimensions.
Define the dimension variables.
Define the pressure-related variables.
Define the state variables.
Define the forcing-related variables.
Define the diagnostics variables.
Close variable definition and the file.
Definition at line 22 of file gmtb_scm_output.f90.
References gmtb_scm_input::check().
Referenced by gmtb_scm_main::gmtb_scm_main_sub().