gmtb_scm_utils
Contains miscellaneous helper subroutines.
Functions/Subroutines
subroutine gmtb_scm_utils::w_to_omega (n_col, n_lev, w, p, T, omega)
subroutine gmtb_scm_utils::copy_data_to_working_dir (dir_name)
Subroutine to copy data needed by the main program to the working directory.
subroutine gmtb_scm_utils::remove_data_from_working_dir ()
Subroutine to remove data needed by the main program from the working directory.
subroutine gmtb_scm_utils::interpolate_to_grid_centers (n_input_levels, input_pres, input_field, pres_l, n_model_levels, model_field, last_initialized)
Subroutine to interpolate a generic input field to the model vertical grid. The index of the last model level initialized is returned so that the calling procedure can patch in a reference profile above.
Detailed Description
Contains miscellaneous helper subroutines.
Function/Subroutine Documentation
subroutine gmtb_scm_utils::copy_data_to_working_dir (character(len=*), intent(in) dir_name)
Subroutine to copy data needed by the main program to the working directory.
The GFS radiation code requires files containing aerosol, CO2, and solar constant data to be in the working directory at runtime. This subroutine temporarily copies the data to the working directory to be removed after the SCM runs.
Parameters
in dir_name the directory where the data is located
Definition at line 24 of file gmtb_scm_utils.f90.
Referenced by gmtb_scm_main::gmtb_scm_main_sub().
subroutine gmtb_scm_utils::interpolate_to_grid_centers (integer, intent(in) n_input_levels, real(kind=dp), dimension(:), intent(in) input_pres, real(kind=dp), dimension(:), intent(in) input_field, real(kind=dp), dimension(:), intent(in) pres_l, integer, intent(in) n_model_levels, real(kind=dp), dimension(:), intent(out) model_field, integer, intent(out) last_initialized)
Subroutine to interpolate a generic input field to the model vertical grid. The index of the last model level initialized is returned so that the calling procedure can patch in a reference profile above.
Parameters
in n_input_levels number of levels in the input profile
in n_model_levels number of model levels
in input_pres pressure levels for the input profile (Pa)
in input_field data from the input profile
in pres_l model pressure levels (Pa)
out model_field interpolated model data profile
out last_initialized last vertical model index that was properly initialized
Todo
Todo Given the exponential decrease in pressure, this routine should probably be converted to using a different method of interpolation (rather tha linear).
Algorithm
Find level where input_pres < pres_l(i)
Once found, calculate the linear interpolation fraction.
Calculate the model field at level i using linear interpolation.
If no level is found, the input sounding does not reach to top of model domain; return the index of the last level initialized.
Definition at line 40 of file gmtb_scm_utils.f90.
Referenced by gmtb_scm_forcing::interpolate_forcing(), and gmtb_scm_setup::set_state().
subroutine gmtb_scm_utils::remove_data_from_working_dir ()
Subroutine to remove data needed by the main program from the working directory.
This subroutine deletes the data that was temporarily copied to the working directory for file cleanliness.
Definition at line 33 of file gmtb_scm_utils.f90.
Referenced by gmtb_scm_main::gmtb_scm_main_sub().