gmtb_scm_main Module Reference
Main SCM program.
Functions/Subroutines
subroutine gmtb_scm_main_sub ()
Detailed Description
Main SCM program.
Author
Grant J. Firl
Date
March-April 2016
The prototype SCM relies heavily on the standalone driver provided by Patrick Tripp. The standalone driver demonstrates how to use the nuopc_physics module to calculate tendencies due to radiation and the rest of the physics suite once, including initialization. It uses 8 columns and it initializes GFS state variables from unformatted binary output files that are (I believe) generated from a GFS model run.
The SCM prototype differs from the standalone driver in several important ways. First, although the state arrays will maintain a `horizontal` dimension (be capable of representing more than one column), the code is designed to use a single column. Second, in order to avoid becoming a GFS-only SCM, input is achieved through host-model agnostic netCDF files. In addition, variables needed to initialize or configure the physics suite are obtained through external namelist files to avoid using GFS output files. Third, the model will have the ability to use different vertical grids and coordinates as well as different time-stepping schemes (initial capability follows the GFS, however). Fourth, the SCM includes functionality to advance through time, calling physics repeatedly, and to replace dynamics/advection with specified large-scale forcing.
The code is organized as follows:
Modules are loaded, GMTB SCM modules first, followed by modules needed for NUOPC driver and GFS physics_suite
Variable definition
Namelist definition
Model configuration either read from file or from command line
Case initialization and forcing file read in
Reference profile for use above initialization data read in
Vertical grid is set up
Array allocation
Interpolate initial conditions to model vertical grid
Read external physics configuration namelist
Follow standalone driver procedure
call gfuncphys to initialize physics lookup tables, etc.
call nuopc_phys_init with parameters read in from namelist
call `set` routines for NEMS derived data types needed by radiation
call nuopc_rad_update and nuopc_rad_run to calculate radiation
call `set` routines for NEMS derived data types needed by remainder of physics
call nuopc_phys_run to calculate remainder of physics
Detailed Algorithm
Function/Subroutine Documentation
subroutine gmtb_scm_main::gmtb_scm_main_sub ()
case-specific initialization and forcing variables
reference profile variables
SCM state variables (variables with appended `i` are interface; variables with appended `l` are layer centered) index order for grid is (horizontal, vertical); index order for state variables is (horizontal, vertical, timesteps); index order for tracer is (horizontal, vertical, tracer_index, timesteps)
interpolated forcing variables
grid coefficients from file
The rest of the variables declared here are from the standalone driver
get_config returns the basic model configuration variables (file or command line)
get_case_init reads and returns case input data
get_reference_profile returns a reference profile to use above the case profile
set up the vertical grid based on the host model (in GFS case, there are also logical flags that set the type of vertical grid)
set up time scheme and number of time steps to keep
once all dimensions are known, allocate the necessary arrays
set_state interpolates the case input data to the model grid and patches in the reference sounding above the case data as necessary
Todo
Todo need to convert w_ls to omega and pass it into state_fldin (is pointer)
Definition at line 79 of file gmtb_scm.f90.
References gmtb_scm_vgrid::calc_gfs_pres_and_exner(), gmtb_scm_utils::copy_data_to_working_dir(), gmtb_scm_input::get_case_init(), gmtb_scm_input::get_config(), gmtb_scm_vgrid::get_gfs_vgrid(), gmtb_scm_input::get_reference_profile(), gmtb_scm_forcing::interpolate_forcing(), gmtb_scm_output::output_append(), gmtb_scm_output::output_init(), gmtb_scm_utils::remove_data_from_working_dir(), and gmtb_scm_setup::set_state().