gmtb_scm_forcing
Contains subroutines to handle the SCM forcing -- interpolating in space and time, etc.
subroutine gmtb_scm_forcing::interpolate_forcing (input_ntimes, input_nlev, input_w_ls, input_omega, input_u_g, input_v_g, input_u_nudge, input_v_nudge, input_T_nudge, input_thil_nudge, input_qt_nudge, input_dT_dt_rad, input_h_advec_thetail, input_h_advec_qt, input_v_advec_thetail, input_v_advec_qt, input_pres, input_time, input_lat, input_lon, input_pres_surf, input_T_surf, n_levels, n_columns, grid_pres, model_time, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, lat, lon, pres_surf, T_surf)
This subroutine interpolates the model forcing, column position, and surface properties to the current model time and to the model grid.
subroutine gmtb_scm_forcing::apply_forcing_leapfrog (n_levels, n_columns, state_tracer, state_T, state_u, state_v, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, exner_l, phii, pres_l, lat, dt, thermo_forcing_type, mom_forcing_type, relax_time, u_force_tend, v_force_tend, T_force_tend, qv_force_tend)
This subroutine updates the state variables due to the model forcing using the leapfrog time integration scheme. It overwrites the state variable arrays where the filtered values from the previous time step are kept. These parts of the state variable arrays are pointed to by the state_fields_in DDT and are later updated by calling nuopc_phys_run.
subroutine gmtb_scm_forcing::apply_forcing_forward_euler (n_levels, n_columns, state_tracer, state_T, state_u, state_v, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, exner_l, phii, pres_l, lat, dt, thermo_forcing_type, mom_forcing_type, relax_time, u_force_tend, v_force_tend, T_force_tend, qv_force_tend)
Detailed Description
Contains subroutines to handle the SCM forcing -- interpolating in space and time, etc.
Function/Subroutine Documentation
[apply_forcing_forward_euler(n_levels, n_columns, state_tracer, state_T, state_u, state_v, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, exner_l, phii, pres_l, lat, dt, thermo_forcing_type, mom_forcing_type, relax_time, u_force_tend, v_force_tend, T_force_tend, qv_force_tend)]subroutine gmtb_scm_forcing::apply_forcing_forward_euler (integer, intent(in) n_levels, integer, intent(in) n_columns, real(kind=dp), dimension(:,:,:,:), intent(inout) state_tracer, real(kind=dp), dimension(:,:,:), intent(inout) state_T, real(kind=dp), dimension(:,:,:), intent(inout) state_u, real(kind=dp), dimension(:,:,:), intent(inout) state_v, real(kind=dp), dimension(:,:), intent(in) w_ls, real(kind=dp), dimension(:,:), intent(in) omega, real(kind=dp), dimension(:,:), intent(in) u_g, real(kind=dp), dimension(:,:), intent(in) v_g, real(kind=dp), dimension(:,:), intent(in) u_nudge, real(kind=dp), dimension(:,:), intent(in) v_nudge, real(kind=dp), dimension(:,:), intent(in) T_nudge, real(kind=dp), dimension(:,:), intent(in) thil_nudge, real(kind=dp), dimension(:,:), intent(in) qt_nudge, real(kind=dp), dimension(:,:), intent(in) dT_dt_rad, real(kind=dp), dimension(:,:), intent(in) h_advec_thil, real(kind=dp), dimension(:,:), intent(in) h_advec_qt, real(kind=dp), dimension(:,:), intent(in) v_advec_thil, real(kind=dp), dimension(:,:), intent(in) v_advec_qt, real(kind=dp), dimension(:,:), intent(in) exner_l, real(kind=dp), dimension(:,:), intent(in) phii, real(kind=dp), dimension(:,:), intent(in) pres_l, real(kind=dp), dimension(:), intent(in) lat, real(kind=dp), intent(in) dt, integer, intent(in) thermo_forcing_type, integer, intent(in) mom_forcing_type, real(kind=dp), intent(in) relax_time, real(kind=dp), dimension(:,:), intent(out) u_force_tend, real(kind=dp), dimension(:,:), intent(out) v_force_tend, real(kind=dp), dimension(:,:), intent(out) T_force_tend, real(kind=dp), dimension(:,:), intent(out) qv_force_tend)
Parameters
in n_columns number of model columns
in n_levels number of model levels
in,out state_tracer model state tracers (horizontal, vertical, tracer, iteration)
in,out state_t model state temperature (horizontal, vertical, iteration)
in,out state_u model state zonal wind (horizontal, vertical, iteration)
in,out state_v model state meridional wind (horizontal, vertical, iteration)
in w_ls large scale w (m/s) (horizontal, vertical)
in omega large scale pressure velocity (Pa/s) (horizontal, vertical)
in u_g geostrophic zonal wind (m/s) (horizontal, vertical)
in v_g geostrophic meridional wind (m/s) (horizontal, vertical)
in u_nudge nudging zonal wind (m/s) (horizontal, vertical)
in v_nudge nudging meridional wind (m/s) (horizontal, vertical)
in t_nudge nudging abs. temperatuere (K) (horizontal, vertical)
in thil_nudge nudging liq. pot. temperature (K) (horizontal, vertical)
in qt_nudge nudging specific humidity (kg/kg) (horizontal, vertical)
in dt_dt_rad radiative heating rate (K/s) (horizontal, vertical)
in h_advec_thil change in theta_il due to horizontal advection (K/s) (horizontal, vertical)
in h_advec_qt change in q_t due to horizontal advection (kg/kg /s) (horizontal, vertical)
in v_advec_thil change in theta_il due to vertical advection (K/s) (horizontal, vertical)
in v_advec_qt change in q_t due to vertical advection (kg/kg /s) (horizontal, vertical)
in dt time step (s)
in lat latitude in radians
in exner_l exner function at model level centers (horizontal, vertical)
in phii geopotential at model level interfaces (horizontal, vertical)
in pres_l pressure at model level centers (horizontal, vertical)
in thermo_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
in mom_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
in relax_time time scale for hor. wind nudging
out u_force_tend sum of all forcing for zonal momentum (horizontal, vertical)
out v_force_tend sum of all forcing for meridional momentum (horizontal, vertical)
out t_force_tend sum of all forcing for temperature (horizontal, vertical)
out qv_force_tend sum of all forcing for water vapor (horizontal, vertical)
Algorithm
Save old state variables (filtered from previous time step)
Initialize forcing sums to zero.
Calculate w_ls and z (height) at model layer interfaces.
Calculate change in state momentum variables due to vertical advection (subsidence).
Calculate tendencies due to vertical advection using same discretization as in previous GFS SCM implmentation (staggered central difference)
 \frac{\partial x}{\partial t}|_{vert. advection} = \frac{w_{k+1}\left(x_{k+1} - x_{k}\right) + w_k\left(x_k - x_{k-1}\right)}{-2\left(z_{k+1}-z_{k}\right)} 
 where $w$ is the vertical velocity on interface levels, $x$ is some state variable on grid centers, $z$ is the height of interface levels. An model layer shares the same index as the interface below.
Handle the top and bottom levels separately using special discretizations.
Add forcing due to geostrophic wind
Calculate Coriolis parameter.
Calculate change in state momentum variables due to nudging.
Add forcing due to prescribed radiation and horizontal advection
Add forcing due to prescribed radiation and horizontal advection
Calculate change in state temperature/moisture variables due to nudging.
Update the state variables using the forward Euler scheme:
 x^{\tau + 1} = x^{\tau} + \Delta t\frac{\partial x}{\partial t}|^\tau_{forcing} 
 $x^{\tau}$ is the value at the previous time step and $\frac{\partial x}{\partial t}|^\tau_{forcing}$ is the sum of forcing terms calculated in this time step.
Definition at line 571 of file gmtb_scm_forcing.f90.
Referenced by gmtb_scm_time_integration::do_time_step().
[apply_forcing_leapfrog(n_levels, n_columns, state_tracer, state_T, state_u, state_v, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, exner_l, phii, pres_l, lat, dt, thermo_forcing_type, mom_forcing_type, relax_time, u_force_tend, v_force_tend, T_force_tend, qv_force_tend)]subroutine gmtb_scm_forcing::apply_forcing_leapfrog (integer, intent(in) n_levels, integer, intent(in) n_columns, real(kind=dp), dimension(:,:,:,:), intent(inout) state_tracer, real(kind=dp), dimension(:,:,:), intent(inout) state_T, real(kind=dp), dimension(:,:,:), intent(inout) state_u, real(kind=dp), dimension(:,:,:), intent(inout) state_v, real(kind=dp), dimension(:,:), intent(in) w_ls, real(kind=dp), dimension(:,:), intent(in) omega, real(kind=dp), dimension(:,:), intent(in) u_g, real(kind=dp), dimension(:,:), intent(in) v_g, real(kind=dp), dimension(:,:), intent(in) u_nudge, real(kind=dp), dimension(:,:), intent(in) v_nudge, real(kind=dp), dimension(:,:), intent(in) T_nudge, real(kind=dp), dimension(:,:), intent(in) thil_nudge, real(kind=dp), dimension(:,:), intent(in) qt_nudge, real(kind=dp), dimension(:,:), intent(in) dT_dt_rad, real(kind=dp), dimension(:,:), intent(in) h_advec_thil, real(kind=dp), dimension(:,:), intent(in) h_advec_qt, real(kind=dp), dimension(:,:), intent(in) v_advec_thil, real(kind=dp), dimension(:,:), intent(in) v_advec_qt, real(kind=dp), dimension(:,:), intent(in) exner_l, real(kind=dp), dimension(:,:), intent(in) phii, real(kind=dp), dimension(:,:), intent(in) pres_l, real(kind=dp), dimension(:), intent(in) lat, real(kind=dp), intent(in) dt, integer, intent(in) thermo_forcing_type, integer, intent(in) mom_forcing_type, real(kind=dp), intent(in) relax_time, real(kind=dp), dimension(:,:), intent(out) u_force_tend, real(kind=dp), dimension(:,:), intent(out) v_force_tend, real(kind=dp), dimension(:,:), intent(out) T_force_tend, real(kind=dp), dimension(:,:), intent(out) qv_force_tend)
This subroutine updates the state variables due to the model forcing using the leapfrog time integration scheme. It overwrites the state variable arrays where the filtered values from the previous time step are kept. These parts of the state variable arrays are pointed to by the state_fields_in DDT and are later updated by calling nuopc_phys_run.
Parameters
in n_columns number of model columns
in n_levels number of model levels
in,out state_tracer model state tracers (horizontal, vertical, tracer, iteration)
in,out state_t model state temperature (horizontal, vertical, iteration)
in,out state_u model state zonal wind (horizontal, vertical, iteration)
in,out state_v model state meridional wind (horizontal, vertical, iteration)
in w_ls large scale w (m/s) (horizontal, vertical)
in omega large scale pressure velocity (Pa/s) (horizontal, vertical)
in u_g geostrophic zonal wind (m/s) (horizontal, vertical)
in v_g geostrophic meridional wind (m/s) (horizontal, vertical)
in u_nudge nudging zonal wind (m/s) (horizontal, vertical)
in v_nudge nudging meridional wind (m/s) (horizontal, vertical)
in t_nudge nudging abs. temperatuere (K) (horizontal, vertical)
in thil_nudge nudging liq. pot. temperature (K) (horizontal, vertical)
in qt_nudge nudging specific humidity (kg/kg) (horizontal, vertical)
in dt_dt_rad radiative heating rate (K/s) (horizontal, vertical)
in h_advec_thil change in theta_il due to horizontal advection (K/s) (horizontal, vertical)
in h_advec_qt change in q_t due to horizontal advection (kg/kg /s) (horizontal, vertical)
in v_advec_thil change in theta_il due to vertical advection (K/s) (horizontal, vertical)
in v_advec_qt change in q_t due to vertical advection (kg/kg /s) (horizontal, vertical)
in dt time step (s)
in lat latitude in radians
in exner_l exner function at model level centers (horizontal, vertical)
in phii geopotential at model level interfaces (horizontal, vertical)
in pres_l pressure at model level centers (horizontal, vertical)
in thermo_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
in mom_forcing_type 1: `revealed forcing`, 2: `horizontal advective forcing`, 3: `relaxation forcing`
in relax_time time scale for hor. wind nudging
out u_force_tend sum of all forcing for zonal momentum (horizontal, vertical)
out v_force_tend sum of all forcing for meridional momentum (horizontal, vertical)
out t_force_tend sum of all forcing for temperature (horizontal, vertical)
out qv_force_tend sum of all forcing for water vapor (horizontal, vertical)
Algorithm
Save old state variables (filtered from previous time step)
Initialize forcing sums to zero.
Calculate w_ls and z (height) at model layer interfaces.
Calculate change in state momentum variables due to vertical advection (subsidence).
Calculate tendencies due to vertical advection using same discretization as in previous GFS SCM implmentation (staggered central difference)
 \frac{\partial x}{\partial t}|_{vert. advection} = \frac{w_{k+1}\left(x_{k+1} - x_{k}\right) + w_k\left(x_k - x_{k-1}\right)}{-2\left(z_{k+1}-z_{k}\right)} 
 where $w$ is the vertical velocity on interface levels, $x$ is some state variable on grid centers, $z$ is the height of interface levels. An model layer shares the same index as the interface below.
Handle the top and bottom levels separately using special discretizations.
Add forcing due to geostrophic wind
Calculate Coriolis parameter.
Calculate change in state momentum variables due to nudging.
Add forcing due to prescribed radiation and horizontal advection
Add forcing due to prescribed radiation and horizontal advection
Calculate change in state temperature/moisture variables due to nudging.
Update the state variables using the leapfrog scheme:
 x^{\tau + 1} = \overline{x^{\tau - 1}} + 2\Delta t\frac{\partial x}{\partial t}|^\tau_{forcing} 
 $\overline{x^{\tau - 1}}$ is the filtered value at the previous time step and $\frac{\partial x}{\partial t}|^\tau_{forcing}$ is the sum of forcing terms calculated in this time step.
Definition at line 308 of file gmtb_scm_forcing.f90.
Referenced by gmtb_scm_time_integration::do_time_step().
[interpolate_forcing(input_ntimes, input_nlev, input_w_ls, input_omega, input_u_g, input_v_g, input_u_nudge, input_v_nudge, input_T_nudge, input_thil_nudge, input_qt_nudge, input_dT_dt_rad, input_h_advec_thetail, input_h_advec_qt, input_v_advec_thetail, input_v_advec_qt, input_pres, input_time, input_lat, input_lon, input_pres_surf, input_T_surf, n_levels, n_columns, grid_pres, model_time, w_ls, omega, u_g, v_g, u_nudge, v_nudge, T_nudge, thil_nudge, qt_nudge, dT_dt_rad, h_advec_thil, h_advec_qt, v_advec_thil, v_advec_qt, lat, lon, pres_surf, T_surf)]subroutine gmtb_scm_forcing::interpolate_forcing (integer, intent(in) input_ntimes, integer, intent(in) input_nlev, real(kind=dp), dimension(:,:), intent(in) input_w_ls, real(kind=dp), dimension(:,:), intent(in) input_omega, real(kind=dp), dimension(:,:), intent(in) input_u_g, real(kind=dp), dimension(:,:), intent(in) input_v_g, real(kind=dp), dimension(:,:), intent(in) input_u_nudge, real(kind=dp), dimension(:,:), intent(in) input_v_nudge, real(kind=dp), dimension(:,:), intent(in) input_T_nudge, real(kind=dp), dimension(:,:), intent(in) input_thil_nudge, real(kind=dp), dimension(:,:), intent(in) input_qt_nudge, real(kind=dp), dimension(:,:), intent(in) input_dT_dt_rad, real(kind=dp), dimension(:,:), intent(in) input_h_advec_thetail, real(kind=dp), dimension(:,:), intent(in) input_h_advec_qt, real(kind=dp), dimension(:,:), intent(in) input_v_advec_thetail, real(kind=dp), dimension(:,:), intent(in) input_v_advec_qt, real(kind=dp), dimension(:), intent(in) input_pres, real(kind=dp), dimension(:), intent(in) input_time, real(kind=dp), dimension(:), intent(in) input_lat, real(kind=dp), dimension(:), intent(in) input_lon, real(kind=dp), dimension(:), intent(in) input_pres_surf, real(kind=dp), dimension(:), intent(in) input_T_surf, integer, intent(in) n_levels, integer, intent(in) n_columns, real(kind=dp), dimension(:,:), intent(in) grid_pres, real(kind=dp), intent(in) model_time, real(kind=dp), dimension(:,:), intent(out) w_ls, real(kind=dp), dimension(:,:), intent(out) omega, real(kind=dp), dimension(:,:), intent(out) u_g, real(kind=dp), dimension(:,:), intent(out) v_g, real(kind=dp), dimension(:,:), intent(out) u_nudge, real(kind=dp), dimension(:,:), intent(out) v_nudge, real(kind=dp), dimension(:,:), intent(out) T_nudge, real(kind=dp), dimension(:,:), intent(out) thil_nudge, real(kind=dp), dimension(:,:), intent(out) qt_nudge, real(kind=dp), dimension(:,:), intent(out) dT_dt_rad, real(kind=dp), dimension(:,:), intent(out) h_advec_thil, real(kind=dp), dimension(:,:), intent(out) h_advec_qt, real(kind=dp), dimension(:,:), intent(out) v_advec_thil, real(kind=dp), dimension(:,:), intent(out) v_advec_qt, real(kind=dp), dimension(:), intent(out) lat, real(kind=dp), dimension(:), intent(out) lon, real(kind=dp), dimension(:), intent(out) pres_surf, real(kind=dp), dimension(:), intent(out) T_surf)
This subroutine interpolates the model forcing, column position, and surface properties to the current model time and to the model grid.
Note
The input forcing file contains forcing for one column, yet the SCM code can accommodate more than one column. Right now, all columns are assumed to have the same forcing.
Parameters
in input_ntimes number of forcing profiles in the input file corresponding to changing forcing in time
in input_nlev number of levels in each input forcing profile
in input_w_ls input large-scale w (m/s) (time, levels)
in input_omega input large-scale omega (Pa/s) (time, levels)
in input_u_g input geostrophic zonal wind (m/s) (time, levels)
in input_v_g input geostrophic meridional wind (m/s) (time, levels)
in input_u_nudge input nudging zonal wind (m/s) (time, levels)
in input_v_nudge input nudging meridional wind (m/s) (time, levels)
in input_t_nudge input nudging abs. temperature (K)) (time, levels)
in input_thil_nudge input nudging liq. pot. temperature (K) (time, levels)
in input_qt_nudge input nudging specific humidity (kg/kg) (time, levels)
in input_dt_dt_rad input radiative heating rate (K/s) (time, levels)
in input_h_advec_thetail input change in theta_il due to horizontal advection (K/s) (time, levels)
in input_h_advec_qt input change in q_t due to horizontal advection (kg/kg /s) (time, levels)
in input_v_advec_thetail input change in theta_il due to vertical advection (K/s) (time, levels)
in input_v_advec_qt input change in q_t due to vertical advection (kg/kg /s) (time, levels)
in input_pres input pressure levels (Pa) (levels)
in input_time input times (s) (time)
in input_lat input latitude (degrees) (time)
in input_lon input longitude (degrees) (time)
in input_pres_surf input surface pressure (Pa) (time)
in input_t_surf input surface temperature (K) (time)
in n_levels number of model levels
in n_columns number of model columns
in grid_pres pressure at grid centers (Pa) (horizontal, vertical)
in model_time current model elapsed time (s)
out w_ls output large scale w (m/s) (horizontal, vertical)
out omega output large scale pressure velocity (Pa/s) (horizontal, vertical)
out u_g output geostrophic zonal wind (m/s) (horizontal, vertical)
out v_g output geostrophic meridional wind (m/s) (horizontal, vertical)
out u_nudge output nudging zonal wind (m/s) (horizontal, vertical)
out v_nudge output nudging meridional wind (m/s) (horizontal, vertical)
out t_nudge output nudging abs. temperature (K) (horizontal, vertical)
out thil_nudge output nudging liq. pot. temperature (K) (horizontal, vertical)
out qt_nudge output nudging specific humidity (kg/kg) (horizontal, vertical)
out dt_dt_rad output radiative heating rate (K/s) (horizontal, vertical)
out h_advec_thil output change in theta_il due to horizontal advection (K/s) (horizontal, vertical)
out h_advec_qt output change in q_t due to horizontal advection (kg/kg /s) (horizontal, vertical)
out v_advec_thil output change in theta_il due to vertical advection (K/s) (horizontal, vertical)
out v_advec_qt output change in q_t due to vertical advection (kg/kg /s) (horizontal, vertical)
out lat output latitude (horizontal)
out lon output longitude (horizontal)
out pres_surf output surface pressure (Pa) (horizontal)
out t_surf output surface temperature (K) (horizontal)
Algorithm
Check for the case where the elapsed model time extends beyond the supplied forcing.
If so, hold the forcing terms constant at the last supplied values. The forcing still needs to be interpolated to the grid.
For all forcing terms, call interpolate_to_grid_centers from gmtb_scm_utils for each variable. This subroutine returns the last vertical index calculated in case forcing terms above the case input needs to be specified.
If the input forcing file does not reach to the model domain top, fill in values above the input forcing file domain with those from the top level.
For this case, no time interpolation is necessary; just set the forcing terms to the vertically-interpolated values.
Set the surface parameters to the last available data.
Convert lat, lon to radians.
When the model elapsed time is within the time-frame specified by the input forcing, the forcing must be interpolated in time and space.
Determine the index in the input file for the time immediately preceeding the model time and determine the linear interpolation value.
For all forcing terms, call interpolate_to_grid_centers from gmtb_scm_utils for each variable for each time level that `bracket` around the current model time. This subroutine returns the last vertical index calculated in case forcing terms above the case input needs to be specified.
If the input forcing file does not reach to the model domain top, fill in values above the input forcing file domain with those from the top level.
Interpolate the forcing terms in time.
Interpolate the surface parameters in time.
Convert lat, lon to radians.
Definition at line 28 of file gmtb_scm_forcing.f90.
References gmtb_scm_utils::interpolate_to_grid_centers().
Referenced by gmtb_scm_main::gmtb_scm_main_sub().