GMTB Single Column Model
Modules
gmtb_scm_forcing
Contains subroutines to handle the SCM forcing -- interpolating in space and time, etc.
gmtb_scm_input
Contains input-related subroutines -- reading in model configuration from file or the command line and reading in the case initial conditions and forcing; also contains reference profile input (temporarily hard-coded).
gmtb_scm_output
Contains output-related subroutines.
gmtb_scm_setup
Contains subroutines to initialize the SCM, including setting the atmospheric state, interpolating initial conditions to the model grid, and patching in a reference sounding above the provided initial conditions.
gmtb_scm_time_integration
Contains subroutines to handle the SCM time stepping.
gmtb_scm_utils
Contains miscellaneous helper subroutines.
gmtb_scm_vgrid
Contains the vertical grid setup routines.
subroutine gmtb_scm_main::gmtb_scm_main_sub ()
Main SCM program.
Detailed Description
Function/Subroutine Documentation
subroutine gmtb_scm_main::gmtb_scm_main_sub ()
Main SCM program.
Author
Grant J. Firl
Date
March-June 2016
The prototype GMTB SCM can be thought of as an update to the existing GFS SCM to 1) use the NGGPS Interoperable Physics Driver (IPD) (and to keep up with its development) and 2) have the capability to run GCSS-style idealized cases. Its initialization draws heavily from the standalone IPD developed by Patrick Tripp at NOAA EMC. Many of the algorithms are heavily influenced by the original GFS SCM, and clues for implementation were also gleaned from how the IPD is implemented (called) in the GSM. The standalone driver demonstrated how to use the nuopc_physics module to calculate tendencies due to radiation and the rest of the physics suite once, including initialization. It uses 8 columns and it initializes GFS state variables from unformatted binary output files that are (I believe) generated from a GFS model run.
The SCM prototype differs from the standalone driver in several important ways. First, although the state arrays will maintain a `horizontal` dimension (be capable of representing more than one column), the code is designed to use a single column. Second, in order to avoid becoming a GFS-only SCM, input is achieved through host-model agnostic netCDF files. In addition, variables needed to initialize or configure the physics suite are obtained through external namelist files to avoid using GFS output files. Third, the model will have the ability to use different vertical grids and coordinates as well as different time-stepping schemes (initial capability follows the GFS, however). Fourth, the SCM includes functionality to advance through time, calling physics repeatedly, and to replace dynamics/advection with specified large-scale forcing.
Main Algorithm
Load the necessary modules for the GTMB SCM.
Load the GMTB SCM modules called from the main program.
Load modules that are needed for using the interoperable physics driver (IPD); includes derived data types (DDTs) and subroutines that are called to drive the physics suite.
Load the modules that are needed for the GFS physics suite
Variable Declarations
Define the variables necessary for the SCM infrastructure.
Define the case-specific initialization and forcing variables.
Define the reference profile variables.
Define the SCM state variables; variables with appended `i` are interface; variables with appended `l` are layer-centered.
index order for grid is (horizontal, vertical);
index order for state variables is (horizontal, vertical, timesteps);
index order for tracer is (horizontal, vertical, tracer_index, timesteps)
Define forcing-related variables (indexing is (horizontal, vertical)).
Define ozone forcing variables (the input forcing terms reside on their own (latitude, levels, time) grid and have 'pl_coeff' terms)
Define h2o forcing variables (the input forcing terms reside on their own (latitude, levels, time) grid and have 'h2o_coeff' terms)
Define GFS-related grid coefficients.
Define variables from the standalone driver.
Define namelist variables (see namelists in model_config).
Define DDT variables used in nuopc_physics.F90
The remaining varialbes are defined in the DDT sections of nuopc_physics.F90
SCM Initialization
Define the namelists that get read in to configure the GFS physics suite. There are separate namelists for GFS physics (general), GFS radiation, GFS surface scheme, GFS clouds, and miscellaneous GFS variables (GFS_tbd)
Call get_config in gmtb_scm_input to fetch the basic model configuration variables (from file or command line)
Call get_case_init in gmtb_scm_input to read and return the case input data.
Call get_reference_profile in gmtb_scm_input to return a reference profile to use above the case profile.
Set up the vertical grid and time-integration scheme based on the host model choice.
Call get_GFS_grid in gmtb_scm_vgrid to read in the necessary coefficients and calculate the pressure-related variables on the grid.
Exit if an unsupported number of levels is specified or the file with grid coefficients cannot be opened.
Set the number of time levels needed to be stored in memory based on the choice of time-stepping scheme for the forcing
Once all dimensions are known, allocate the necessary arrays.
Todo
Todo state_tracer and temp_tracer should use a variable for dimension 3.
Read in namelists for GFS model control variables rather than read a GFS output file as in the standalone driver.
Todo
Todo These namelists are GFS physics-specific. This should probably be placed in the host model switch above.
Todo
Todo The physics and dynamics timesteps are equal in the SCM. This may need to be changed in the future.
Since some GFS initialization routines look for datasets in the working directory, use a system call to copy runtime data into the working directory.
Call set_state in gmtb_scm_setup to interpolate the case input data to the model grid and patch in the reference sounding above the case data as necessary.
Initialize the model elapsed time and model time step iteration counter.
Call interpolate_forcing in gmtb_scm_forcing to interpolate the input forcing to the model grid and model time.
Todo
Todo need to convert w_ls to omega and pass it into state_fldin (is pointer)
Put initial date (idate) into idat format for rad_update. (Is this needed? Done in nuopc_phys_init...)
Set jdat (current date) to idat
Set timesteps for longwave and shortwave radiation.
Set the lmfshal and lmfdeep2 flags as done in gloopr (with comment: `set up parameters for Xu & Randall's cloudiness computation`)
Initialize the model time step.
Initialize the longwave/shortwave radiation flags to True.
Convert input latitude/longitude to radians and calculate sin and cos of latitude.
Todo
Todo Check that solhr is initialized correctly.
Initialize physics substep to 1, since physics time step = dynamics time step and there are no substeps.
Initialize a random number array needed for RAS or old SAS
Call ras_init if RAS is the chosen convection scheme.
Todo
Todo Not tested yet.
Todo
Todo hprim_v is an array of surface-related variables that are geographic location dependent that are used in the gravity wave drag parameterization. in Fletcher's SCM, these are read in; presumably generated with outside scripts/code based on an orography dataset and a given location. These have no influence on maritime cases, but will need to be addressed for land cases.
Todo
Todo Need to understand what this (adjtrc) does...
Call output_init in gmtb_scm_output to create and initialize the output file.
Write out the initial profiles and forcing.
The following code is mostly copied from the NUOPC standalone driver.
The `*_readin` subroutines in the standalone driver are not used in the SCM since the variables are initialized in another way. Similarly, the `*_saveout` routines are not called since the SCM is not being used for regression testing.
Call nuopc_phys_init in nuopc_physics.F90.
This routine initializes idat, fills in mdl_parm DDT, calls gfuncphys (funcphys.f), rad_initialize (rad_initialize.f), and set_soilveg (set_soilveg.f)
Set deltim = 0.5*dt for first forward time step.
Call the `setrad` methods of the NUOPC DDTs in preparation for nuopc_rad_update and nuopc_rad_run.
The dynamic_parameters DDT is the only DDT that has mostly non-pointers. This setrad routine must be called before nuopc_rad_update and nuopc_rad_run if the underlying parameters have changed.
For the first time step, the state_fields_in DDT points to the filtered values.
Todo
Todo vvl is initialized to zero, but should be omega converted from large-scale w forcing.
Call nuopc_rad_update from nuopc_physics.F90. This is a wrapper to the radupdate found in grrad.f used to `update time-sensitive data used by radiation` code
Call nuopc_rad_run from nuopc_physics.F90. This is a wrapper to the grrad subroutine in grrad.f that is used to `set up and invoke main radiation calls.`
Todo
Todo Calling dyn_parmsetphys resets slag, sdec, cdec to 0; need to call nuopc_rad_update again? -no way to get these values from dyn_parm (private)
Call the `setphys` methods of the NUOPC DDTs in preparation for the nuopc_phys_run call.
The state_fields_in DDT is filled with the time-filtered values of the state variables.
For the leapfrog scheme, the state_fields_out DDT is filled with the unfiltered values of the state variables. The nuopc_phys_run call updates the unfiltered state variables.
Call nuopc_phys_run from nuopc_physics.F90. This is simply a wrapper to gbphys which is the GFS atmospheric physics driver routine.
Time Loop
Description
The filtered leapfrog scheme can be represented as follows:
 \frac{x^{\tau + 1} - \overline{x^{\tau - 1}}}{2\Delta t}=F^\tau 
 where $x^{\tau + 1}$ is the value of variable $x$ at time $\tau + 1$, $\overline{x^{\tau - 1}}$ is its filtered value at time $\tau - 1$, $\Delta t$ is the time step, and $F^\tau$ is the collection of processes that change $x$ at time $\tau$. The Robert-Asselin filtered value of $x$ is given by
 \overline{x^\tau}=(1-c)x^\tau + 0.5c\left(x^{\tau +1} + \overline{x^{\tau - 1}}\right) 
 where $c$ is the filtering constant. This scheme is implemented in the code as follows:
For the current time step (going to time $\tau + 1$), we have available at the beginning of the time step the filtered value $\overline{x^{\tau-1}}$ and the unfiltered value $x^\tau$. These are represented by state_x(:,:,1) and state_x(:,:,2) in the code, respectively.
At the beginning of the time step, these values are saved in a temporary array for use in the filtering step later.
In the do_time_step routine, nuopc_rad_run uses state_x(:,:,1) (or $\overline{x^{\tau -1}}$) as input to calculate the heating rate at time $\tau$.
In the routine apply_forcing_leapfrog (in gmtb_scm_forcing), two things happen:
Tendencies of the state variables due to the forcing are calculated for time $\tau$ ($F^\tau$ above).
The state variables are stepped forward in time using
 x^{\tau+1}=\overline{x^{\tau -1}} + 2\Delta tF^\tau 
 In the code, state_x(:,:,1) is simply updated. This variable is pointed to by the state_fields_in NUOPC DDT and is used as input for the physics call. At this point in the code, this variable no longer represents the filtered values from the previous time step, but the unfiltered state variables after their change due to the forcing and before their changes due to the physics.
During the call to nuopc_phys_run, state_x(:,:,1) is used as the starting point for the state variable and its unfiltered value is updated by the physics and stored in state_x(:,:,2) (which state_fields_out points to). This is considered $x^{\tau +1}$.
Finally, using $x^{\tau +1}$ just calculated, and the saved values of $\overline{x^{\tau-1}}$ and $x^\tau$, the filtered value $\overline{x^\tau}$ is calculated by the subroutine filter in gmtb_scm_time_integration to be used in the next iteration.
Algorithm
Convert various calling frequencies to time step numbers.
Set all time steps equal to the `master` SCM time step
Update dyn_parm DDT with new deltim.
Based on the time-integration method chosen, start the model time loop. Currently, only filtered-leapfrog is implemented.
Start the main time loop.
Calculate the elapsed model time.
Save previously unfiltered state as temporary for use in the time filter.
Call interpolate_forcing from gmtb_scm_forcing to interpolate the forcing terms to the model grid and time.
Update the pressure (and related variables) on the grid levels since some cases have a time-dependent surface pressure.
Recalculate sin and cos of latitude since xlon and xlat are time-dependent for some cases. (Column is moving in geographic space)
Before the time step is executed, perform various operations that are found in GLOOPR and GLOOPB before the physics time steps are executed in the GSM.
GLOOPR code:
Determine if SW, LW radiation needs to be called and set logical flags.
Update jdat (yr, mon, day, t-zone, hr, min, sec, mil-sec) given the elapsed model time and the initial time.
Set up random numbers for subgrid cloudiness in radiation
Grab variables from `3D arrays saved for restart`, calculate minimum large ice fraction ?
Todo
Todo Go back through GLOOPR to determine what needs to be included here.
GLOOPB code:
Set up random number array needed for RAS and old SAS (should probably only do this if these schemes are active)
Set geopotential and exner functions to zero to force gbphys to recalculate? Set maximum depth of shallow convection.
Zero out convective scheme quantities before the call to gbphys.
Zero out `temperature change due to radiative heating per time step (K)` before call to gbphys.
Zero out `mass change due to moisture variation` before call to gbphys.
Update dynparm physics parameters before call to gbphys.
Update dynparm radiation parameters before call to grrad. (should this only be called on a radiation time step?)
Call do_time_step in gmtb_scm_time_integration. This routine calls nuopc_rad_update and nuopc_rad_run (if necessary), apply_forcing_leapfrog from gmtb_scm_forcing, and nuopc_phys_run. Each updates var(:,:,2), or the unfiltered values of state variables.
Call filter in gmtb_scm_time_integration to perform the Asselin time filtering of the state variables.
Todo
Todo tracers besides water vapor do not need to be filtered (is this right?)
Execute code that is found in GLOOPR, GLOOPB after the time step is executed.
The following code is from GLOOPR after the call to radiation. Since the calls to radiation and the rest of the physics in GSM are separate, this code might need to be executed before the call to nuopc_phys_run (gbphys), so I'm not sure if it is OK to put here...
Set some variables from the radiation output variables.
Write output (snapshot of filtered state variables) on the output frequency by calling output_append from gmtb_scm_output.
Clean Up
Finally, clean up the data copied to the working directory.
Definition at line 31 of file gmtb_scm.f90.
References gmtb_scm_vgrid::calc_gfs_pres_and_exner(), gmtb_scm_utils::copy_data_to_working_dir(), gmtb_scm_time_integration::do_time_step(), gmtb_scm_time_integration::filter(), gmtb_scm_input::get_case_init(), gmtb_scm_input::get_config_nml(), gmtb_scm_vgrid::get_gfs_vgrid(), gmtb_scm_input::get_reference_profile(), gmtb_scm_forcing::interpolate_forcing(), gmtb_scm_output::output_append(), gmtb_scm_output::output_init(), gmtb_scm_utils::remove_data_from_working_dir(), and gmtb_scm_setup::set_state().
Referenced by gmtb_scm().