FROM ubuntu:24.04

# Extend and update the package registry
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      ca-certificates \
      curl \
      wget \
      gpg \
      binutils \
      g++ \
      gcc \
      libc-dev \
      make \
      git \
      gfortran>=14 \
      cmake \
      libopenmpi-dev \
      openmpi-bin \
      ksh \
      m4 \
      tcsh \
      time \
      vim \
      file \
      libxml2

ENV FC=mpif90 CC=mpicc CXX=mpicxx