#
# Install NCEPlibs and its dependencies
#

ARG TOOLCHAIN=gnu
FROM add-netcdf:${TOOLCHAIN}

ENV NCEPLIBS_DIR=/opt/nceplibs

# Install bacio library
ENV BACIO_VERSION=2.4.1
RUN mkdir -p $NCEPLIBS_DIR/src && cd $NCEPLIBS_DIR/src \
  && git clone --depth 1 --shallow-submodules -b v${BACIO_VERSION} --recursive https://github.com/NOAA-EMC/NCEPLIBS-bacio \
  && mkdir NCEPLIBS-bacio/build && cd NCEPLIBS-bacio/build \
  && cmake -DCMAKE_INSTALL_PREFIX=$NCEPLIBS_DIR -DBUILD_TESTING=OFF .. \
  && make VERBOSE=1 -j$(nproc) \
  && make install \
  && cd $NCEPLIBS_DIR/src && rm -rf NCEPLIBS-bacio

# Install IP-library
ENV IP_VERSION=5.4.1
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
       liblapack-dev \
  && rm -rf /var/lib/apt/lists/* \
  && cd $NCEPLIBS_DIR/src \
  && git clone --depth 1 --shallow-submodules -b v${IP_VERSION} --recursive https://github.com/NOAA-EMC/NCEPLIBS-ip \
  && mkdir NCEPLIBS-ip/build && cd NCEPLIBS-ip/build \
  && cmake -DCMAKE_INSTALL_PREFIX=$NCEPLIBS_DIR -DBUILD_TESTING=OFF .. \
  && make VERBOSE=1 -j$(nproc) \
  && make install \
  && cd $NCEPLIBS_DIR/src && rm -rf NCEPLIBS-ip

# Install w3emc library
ENV W3EMC_VERSION=2.11.0
RUN cd $NCEPLIBS_DIR/src \
  && git clone --depth 1 --shallow-submodules -b v${W3EMC_VERSION} --recursive https://github.com/NOAA-EMC/NCEPLIBS-w3emc \
  && mkdir NCEPLIBS-w3emc/build && cd NCEPLIBS-w3emc/build \
  && cmake -DCMAKE_INSTALL_PREFIX=$NCEPLIBS_DIR -DBUILD_TESTING=OFF .. \
  && make VERBOSE=1 -j$(nproc) \
  && make install \
  && rm -rf $NCEPLIBS_DIR/src

ENV bacio_DIR=/opt/nceplibs/lib/cmake/bacio
ENV ip_DIR=/opt/nceplibs/lib/cmake/ip
ENV w3emc_DIR=/opt/nceplibs/lib/cmake/w3emc
