FROM ubuntu:24.04

ARG GNU_VERSION='13'

# Extend and update the package registry
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      ca-certificates \
      curl \
      wget \
      gpg \
      binutils \
      g++ \
      gcc \
      libc-dev \
      make \
      cmake \
      git 

# Set default compiler executables
ENV FC=gfortran CC=gcc CXX=g++
ENV MPICC="mpicc -cc=gcc"
ENV MPIF90="mpif90 -fc=gfortran"
