#
# Install NCEPlibs and its dependencies
#

ARG TOOLCHAIN
FROM add-netcdf:$TOOLCHAIN

ENV NCEPLIBS_DIR=/opt/nceplibs

# Install bacio library
ENV BACIO_VERSION=2.4.1
RUN mkdir -p $NCEPLIBS_DIR/src && cd $NCEPLIBS_DIR/src \
  && git clone -b v${BACIO_VERSION} --recursive https://github.com/NOAA-EMC/NCEPLIBS-bacio \
  && mkdir NCEPLIBS-bacio/build && cd NCEPLIBS-bacio/build \
  && cmake -DCMAKE_INSTALL_PREFIX=$NCEPLIBS_DIR .. \
  && make VERBOSE=1 -j \
  && make install

# Install SP-library
ENV SP_VERSION=2.3.3
RUN cd $NCEPLIBS_DIR/src \
  && git clone -b v${SP_VERSION} --recursive https://github.com/NOAA-EMC/NCEPLIBS-sp \
  && mkdir NCEPLIBS-sp/build && cd NCEPLIBS-sp/build \
  && cmake -DCMAKE_INSTALL_PREFIX=$NCEPLIBS_DIR .. \
  && make VERBOSE=1 -j \
  && make install

# Install w3emc library
ENV W3EMC_VERSION=2.11.0
RUN cd $NCEPLIBS_DIR/src \
  && git clone -b v${W3EMC_VERSION} --recursive https://github.com/NOAA-EMC/NCEPLIBS-w3emc \
  && mkdir NCEPLIBS-w3emc/build && cd NCEPLIBS-w3emc/build \
  && cmake -DCMAKE_INSTALL_PREFIX=$NCEPLIBS_DIR .. \
  && make VERBOSE=1 -j \
  && make install

ENV bacio_DIR=/opt/nceplibs/lib/cmake/bacio
ENV sp_DIR=/opt/nceplibs/lib/cmake/sp
ENV w3emc_DIR=/opt/nceplibs/lib/cmake/w3emc