#
# Install Python3 and a small set of packages
#

ARG TOOLCHAIN
FROM add-netcdf:$TOOLCHAIN

# Install Python
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      python-is-python3 \
      python3 \
      python3-pip \
 && rm -rf /var/lib/apt/lists/*

# Install essential packages
#   we install netCDF4 instead of xarray[io] to omit unnecessary packages
RUN pip3 install  --break-system-packages \
      dask[array] \
      netCDF4 \
      numpy \
      xarray

# Install packages for the validation plot generation
#   we install scipy instead of xarray[accel] to omit unnecessary packages
RUN pip3 install  --break-system-packages \
      colorcet \
      matplotlib \
      scipy \
      seaborn
