FROM ubuntu:24.04

ARG GNU_VERSION=14

# Extend and update the package registry
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      ca-certificates \
      curl \
      wget \
      gpg \
      binutils \
      gfortran-$GNU_VERSION \
      g++ \
      gcc \
      libc-dev \
      make \
      cmake \
      git 

# Set default compiler executables
ENV FC=gfortran CC=gcc CXX=g++
