#
# Install Parallel NetCDF Fortran and its dependencies
#

ARG TOOLCHAIN
FROM minimal-toolchain:$TOOLCHAIN

# Set environment variables for PnetCDF installation
ENV PNETCDF_VERSION=1.14.1
ENV PNETCDF_PREFIX=/opt/pnetcdf
ENV PATH="${PNETCDF_PREFIX}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PNETCDF_PREFIX}/lib:{$LD_LIBRARY_PATH}"
ENV PKG_CONFIG_PATH="${PNETCDF_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"

# Update and install necessary build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    gfortran \
    automake \
    libtool \
    m4 \
    && rm -rf /var/lib/apt/lists/*

# Download, compile, and install PnetCDF
WORKDIR /tmp
RUN wget https://parallel-netcdf.github.io/Release/pnetcdf-${PNETCDF_VERSION}.tar.gz \
    && tar xzf pnetcdf-${PNETCDF_VERSION}.tar.gz \
    && cd pnetcdf-${PNETCDF_VERSION} \
    && autoreconf -i \
    && ./configure --prefix=${PNETCDF_PREFIX} --enable-shared --disable-static MPICC=mpicc\
    && make -j 8 install \
    && cd /tmp \
    && rm -rf pnetcdf-${PNETCDF_VERSION} pnetcdf-${PNETCDF_VERSION}.tar.gz

# Add PnetCDF library path to the environment
ENV PATH="${PNETCDF_PREFIX}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PNETCDF_PREFIX}/lib:${LD_LIBRARY_PATH}"
