#
# Install NetCDF Fortran and its dependencies
#

ARG TOOLCHAIN
FROM minimal-toolchain:$TOOLCHAIN

# Install the dependencies
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      curl \
      libnetcdf-dev \
 && rm -rf /var/lib/apt/lists/*

# Install NetCDF Fortran
#   The version must be compitible with NetCDF C installed above
ARG NFVERSION
ENV NFVERSION=$NFVERSION
ARG FC
ENV FC=$FC
ARG CC
ENV CC=$CC
ARG CXX
ENV CXX=$CXX


#RUN curl https://downloads.unidata.ucar.edu/netcdf-fortran/$NFVERSION/netcdf-fortran-$NFVERSION.tar.gz | tar xz \
#  && cd netcdf-fortran-$NFVERSION \
#  && { ./configure \
#         CFLAGS='-O2' \
#         FCFLAGS='-O2 -fPIC' \
#         --disable-static \ 
#         --prefix=/usr || \
#       { cat ./config.log; exit 1; } }
#RUN cd netcdf-fortran-$NFVERSION \
#  && make -j \
#  && make install \
#  && cd .. \
#  && rm -rf netcdf-fortran-$NFVERSION \
#  && ldconfig

RUN wget https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v$NFVERSION.tar.gz \
    && tar -xzf v$NFVERSION.tar.gz \
    && cd netcdf-fortran-$NFVERSION \
    && CC=$CC FC=$FC CXX=$CXX ./configure --prefix=/usr \
    && make -j && make install