default_physics_namelists = {"SCM_csawmg":"input_csawmg.nml",
                            "SCM_GSD_v1":"input_GSD_v1.nml",
                            "SCM_GFS_v15p2":"input_GFS_v15p2.nml",
                            "SCM_GFS_v16beta":"input_GFS_v16beta.nml",
                            "SCM_GFS_v15p2_no_nsst":"input_GFS_v15p2.nml",
                            "SCM_GFS_v16beta_no_nsst":"input_GFS_v16beta.nml",
                            "SCM_GFS_v15p2_RRTMGP":"input_GFS_v15p2_RRTMGP.nml",
                            "SCM_GFS_v16beta_RRTMGP":"input_GFS_v16beta_RRTMGP.nml",
                            "SCM_GFS_v15p2_noahmp":"input_GFS_v15p2_noahmp.nml",
                            "SCM_GFS_v15p2_MYJ":"input_GFS_v15p2_MYJ.nml",
                            "SCM_GFS_v15p2_FA":"input_GFS_v15p2_FA.nml",
                            "SCM_GFS_v15p2_YSU":"input_GFS_v15p2_YSU.nml",
                            "SCM_GFS_v15p2_saYSU":"input_GFS_v15p2_saYSU.nml",
                            "SCM_GFS_v15p2_ACM":"input_GFS_v15p2_ACM.nml",
                            "HAFS_v0_hwrf":"input_HAFS_v0_hwrf.nml",
                            "HAFS_v0_hwrf_thompson":"input_HAFS_v0_hwrf_thompson.nml",
                            "SCM_RRFS_v1beta":"input_RRFS_v1beta.nml"
                            }