gmtb_scm_setup
Contains subroutines to initialize the SCM, including setting the atmospheric state, interpolating initial conditions to the model grid, and patching in a reference sounding above the provided initial conditions.
subroutine gmtb_scm_setup::set_state (n_input_levels, input_pres, input_qt, input_thetail, input_ql, input_qi, input_u, input_v, input_ozone, n_model_levels, n_columns, ntoz, ntcw, pres_l, n_smooth_levels, n_ref_levels, ref_pres, ref_qv, ref_T, ref_ozone, state_tracer, state_T, state_u, state_v)
Subroutine to interpolate the initial conditions to the model grid and set the state variables.
subroutine gmtb_scm_setup::patch_in_ref (last_index_init, n_levels_smooth, n_ref_levels, ref_pres, ref_field, pres_l, n_model_levels, model_field, err)
Subroutine to patch in a reference profile (smoothly) above a given model level.
Detailed Description
Contains subroutines to initialize the SCM, including setting the atmospheric state, interpolating initial conditions to the model grid, and patching in a reference sounding above the provided initial conditions.
Function/Subroutine Documentation
subroutine gmtb_scm_setup::patch_in_ref (integer, intent(inout) last_index_init, integer, intent(in) n_levels_smooth, integer, intent(in) n_ref_levels, real(kind=dp), dimension(:), intent(in) ref_pres, real(kind=dp), dimension(:), intent(in) ref_field, real(kind=dp), dimension(:), intent(in) pres_l, integer, intent(in) n_model_levels, real(kind=dp), dimension(:), intent(inout) model_field, integer, intent(out) err)
Subroutine to patch in a reference profile (smoothly) above a given model level.
Parameters
in,out last_index_init last vertical model index that was initialized
in n_levels_smooth number of levels below the last initialized model level to start smoothing in the reference profile
in n_ref_levels number of reference profile levels
in n_model_levels number of model levels
in ref_pres reference profile pressure levels (Pa)
in ref_field reference profile data
in pres_l model pressure levels (Pa)
in,out model_field model profile data
out err error code to return to calling procedure (0: no error, 1: reference profile shorter than input, 2: reference profile shorter than model domain)
Algorithm
Check for the reference profile being shorter than the input (error code 1), or shorter than the model domain (error code 2).
Recalculate the model data profile n_levels_smooth below the last index calculated in order to provided a smoother transition to the reference profile.
smooth_frac is the fraction of the reference value to use (remainder is model field already calculated)
First, interpolate reference profile to model levels.
Then, recalculate field at model level using smooth_frac
Above the highest model level specified in the input, just interpolate to the reference profile.
If the reference profile does not proceed to the top of the model domain, keep track of the highest level initialized.
If the reference profile was shorter than the model domain, extrapolate to fill in the missing values (temporary solution).
Definition at line 143 of file gmtb_scm_setup.f90.
Referenced by gmtb_scm_setup::set_state().
[set_state(n_input_levels, input_pres, input_qt, input_thetail, input_ql, input_qi, input_u, input_v, input_ozone, n_model_levels, n_columns, ntoz, ntcw, pres_l, n_smooth_levels, n_ref_levels, ref_pres, ref_qv, ref_T, ref_ozone, state_tracer, state_T, state_u, state_v)]subroutine gmtb_scm_setup::set_state (integer, intent(in) n_input_levels, real(kind=dp), dimension(:), intent(in) input_pres, real(kind=dp), dimension(:), intent(in) input_qt, real(kind=dp), dimension(:), intent(in) input_thetail, real(kind=dp), dimension(:), intent(in) input_ql, real(kind=dp), dimension(:), intent(in) input_qi, real(kind=dp), dimension(:), intent(in) input_u, real(kind=dp), dimension(:), intent(in) input_v, real(kind=dp), dimension(:), intent(in) input_ozone, integer, intent(in) n_model_levels, integer, intent(in) n_columns, integer, intent(in) ntoz, integer, intent(in) ntcw, real(kind=dp), dimension(:,:), intent(in) pres_l, integer, intent(in) n_smooth_levels, integer, intent(in) n_ref_levels, real(kind=dp), dimension(:), intent(in) ref_pres, real(kind=dp), dimension(:), intent(in) ref_qv, real(kind=dp), dimension(:), intent(in) ref_T, real(kind=dp), dimension(:), intent(in) ref_ozone, real(kind=dp), dimension(:,:,:), intent(out) state_tracer, real(kind=dp), dimension(:,:), intent(out) state_T, real(kind=dp), dimension(:,:), intent(out) state_u, real(kind=dp), dimension(:,:), intent(out) state_v)
Subroutine to interpolate the initial conditions to the model grid and set the state variables.
Parameters
in n_input_levels number of levels in the case input data
in n_model_levels number of model levels
in n_columns number of columns (should be 1 for SCM)
in n_smooth_levels number of model levels over which to smoothly transition to the reference profile
in n_ref_levels number of levels in the reference profile
in ntoz tracer array index for ozone
in ntcw tracer array index for cloud water
in input_pres pressure levels for the case input (Pa)
in input_qt total water specific humidity for the case input (kg kg^-1)
in input_thetail liquid-ice water potential temperature for the case input (K)
in input_ql liquid water specific humidity for the case input (kg kg^-1)
in input_qi ice water specific humidity for the case input (kg kg^-1)
in input_u east-west wind for the case input (m s^-1)
in input_v north-south wind for the case input (m s^-1)
in input_ozone ozone concentration for the case input (kg kg^-1)
in pres_l model pressure levels (Pa) (n_columns, n_model_levels)
in ref_pres pressure levels for the reference profile (Pa)
in ref_qv water vapor specific humidity for the reference profile (kg kg^-1)
in ref_t temperature for the reference profile (K)
in ref_ozone ozone concentratin for the reference profile (kg kg^-1)
out state_tracer water vapor specific humidity for the model state, ozone, cloud water [all (kg kg^-1)]
out state_t temperature for the model state (K)
out state_u east-west wind for the model state (m s^-1)
out state_v north-south wind for the model state (m s^-1)
Algorithm
Calculate water vapor from total water, suspended liquid water, and suspended ice.
Todo
Todo When patching in a reference sounding, need to handle the case when the reference sounding is too short; patch_in_ref checks for the case, but as of now, it just extrapolates where it needs to and returns an error code; error should be handled here or passed up to the main program.
For each column, interpolate the water vapor to the model grid.
If the input domain does not span the model domain, patch in McClatchey tropical standard atmosphere (smoothly over a number of levels) above.
Calculate the input absolute temperature from input pressure, theta_il, ql, and qi.
For each column, interpolate the temperature to the model grid.
If the input domain does not span the model domain, patch in McClatchey tropical standard atmosphere (smoothly over a number of levels) above.
For each column, interpolate the u-wind to the model grid.
The standard atmosphere doesn't have wind data; assume zero-gradient above the input data.
For each column, interpolate the v-wind to the model grid.
The standard atmosphere doesn't have wind data; assume zero-gradient above the input data.
For each column, interpolate the ozone to the model grid.
If the input domain does not span the model domain, patch in McClatchey tropical standard atmosphere (smoothly over a number of levels) above.
Definition at line 26 of file gmtb_scm_setup.f90.
References gmtb_scm_utils::interpolate_to_grid_centers(), and gmtb_scm_setup::patch_in_ref().
Referenced by gmtb_scm_main::gmtb_scm_main_sub().