name: Build the CCPP-SCM in a container

on:
  push:
    branches:
      - feature/containerized_ci
  pull_request:
  workflow_dispatch:

jobs:
  build_scm_container:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        fortran-compiler: [ifx, gfortran, nvfortran]
        build-type:       [Release, Debug]
        include:
        # Set container images for each compiler
        - fortran-compiler: ifx
          image: dustinswales/ccpp-scm-ci:oneapi
        - fortran-compiler: gfortran
          image: dustinswales/ccpp-scm-ci:gnu
        - fortran-compiler: nvfortran
          image: dustinswales/ccpp-scm-ci:nvhpc
    container:
      image: ${{ matrix.image }}
    # Environmental variables
    env:
      #NetCDF_Fortran_ROOT: /opt/netcdf-fortran
      NFHOME: /usr

    # Workflow steps
    steps:
    #############################################################
    # NOTE
    # $ echo ${{ github.workspace }}
    # /home/runner/work/<REPO_NAME>/<REPO_NAME>
    # $ echo $GITHUB_WORKSPACE
    # /__w/<REPO_NAME>/<REPO_NAME>
    #############################################################
    - name: Checkout SCM code (/__w/ccpp-scm/ccpp-scm)
      uses: actions/checkout@v4

    - name: Install Required Tools
      run: |
        apt-get update

    - name: Initialize Submodules
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        git submodule update --init --recursive

    #- name: Setup MPI Paths
    #  run: |
    #    echo "PATH=/opt/intel/oneapi/mpi/latest/bin:${PATH}" >> $GITHUB_ENV
    #    echo "LD_LIBRARY_PATH=/opt/intel/oneapi/mpi/latest/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV

    - name: Configure Build with CMake
      run: |
        cd $GITHUB_WORKSPACE/scm
        mkdir bin && cd bin
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ../src

    - name: Build SCM
      run: |
        cd $GITHUB_WORKSPACE/scm/bin
        make -j4
