name: Build the CCPP-SCM in a container

on:
  push:
    branches:
      - feature/containerized_ci
  pull_request:
  workflow_dispatch:

jobs:
  build_scm_container:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        fortran-compiler: [ifx]
        build-type:       [Release, Debug]
        include:
        # Set container images
        - fortran-compiler: ifx
          image: dustinswales/ccpp-scm-ci:oneapi
    container:
      image: ${{ matrix.image }} 
    # Environmental variables
    env:
      FC:       ${{ matrix.fortran-compiler }}
      NetCDF_Fortran_ROOT: /opt/netcdf-fortran
      SCM_ROOT: /__w/ccpp-scm/ccpp-scm
      suites:   SCM_GFS_v15p2,SCM_GFS_v16,SCM_GFS_v16_RRTMGP,SCM_GFS_v17_p8,SCM_HRRR,SCM_RRFS_v1beta,SCM_RAP,SCM_WoFS_v0,SCM_GFS_v15p2_ps,SCM_GFS_v16_ps,SCM_GFS_v16_RRTMGP_ps,SCM_GFS_v17_p8_ps,SCM_HRRR_ps,SCM_RRFS_v1beta_ps,SCM_RAP_ps,SCM_WoFS_v0_ps,SCM_HRRR_gf,SCM_HRRR_gf_ps

    # Workflow steps
    steps:

    - name: Checkout SCM code
      uses: actions/checkout@v4

    - name: Initialize Submodules
      run: |
        git config --global --add safe.directory ${SCM_ROOT}
        cd ${SCM_ROOT}
        git submodule update --init --recursive
        pwd
        echo "-----0"
        ls /opt
        echo "-----1"
        ls /__w/
        echo "-----2"
        ls /opt/nceplibs/NCEPLIBS-bacio/

    - name: Configure Build with CMake
      run: |
        cd ${SCM_ROOT}/scm
        mkdir bin && cd bin
        cmake -DCCPP_SUITES=${suites} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ../src

    - name: Build SCM
      run: |
        cd ${SCM_ROOT}/scm/bin
        make -j4
