name: Build the CCPP-SCM in a container

on:
  push:
    branches:
      - feature/containerized_ci
  pull_request:
  workflow_dispatch:

jobs:
  build_scm_container:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        fortran-compiler: [ifx]
        build-type:       [Release, Debug]
        include:
        # Set container images
        - fortran-compiler: ifx
          image: dustinswales/ccpp-scm-ci:oneapi
    container:
      image: ${{ matrix.image }} 
    # Environmental variables
    env:
      FC:       ${{ matrix.fortran-compiler }}
      NetCDF_Fortran_ROOT: /opt/netcdf-fortran
      SCM_ROOT: /__w/ccpp-scm/ccpp-scm
      suites_v16:  SCM_GFS_v16,SCM_GFS_v16_ps,SCM_GFS_v16_RRTMGP,SCM_GFS_v16_RRTMGP_ps
      suites_v17:  SCM_GFS_v17_p8,SCM_GFS_v17_p8_ps
      suites_wofs: SCM_WoFS_v0,SCM_WoFS_v0_ps,
      suites_rrfs: SCM_HRRR_gf,SCM_HRRR_gf_ps,SCM_RRFS_v1beta,SCM_RRFS_v1beta_ps
      suites_old:  SCM_GFS_v15p2,SCM_GFS_v15p2_ps,SCM_HRRR,SCM_HRRR_ps,SCM_RAP,SCM_RAP_ps

    # Workflow steps
    steps:
    #############################################################
    # NOTE
    # $ echo ${{ github.workspace }}
    # /home/runner/work/<REPO_NAME>/<REPO_NAME>
    # $ echo $GITHUB_WORKSPACE
    # /__w/<REPO_NAME>/<REPO_NAME>
    #############################################################
    - name: Checkout SCM code (/__w/ccpp-scm/ccpp-scm)
      uses: actions/checkout@v4

    - name: Initialize Submodules
      run: |
        git config --global --add safe.directory ${SCM_ROOT}
        cd ${SCM_ROOT}
        git submodule update --init --recursive
        pwd
        echo "-----0"
        echo "-----1"
        #echo "-----2"
        #ls /__w/_actions/actions/

    - name: Set up the oneAPI environment variables
      # Source setvars.sh to make compilers and MPI wrappers (mpiicc, mpiifort) available
      run: |
        source /opt/intel/oneapi/setvars.sh
        # Make environment variables available to subsequent steps in the workflow
        echo "ONEAPI_ROOT=/opt/intel/oneapi" >> $GITHUB_ENV
        #echo "/opt/intel/oneapi/mpi/latest/bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure Build with CMake
      run: |
        cd ${SCM_ROOT}/scm
        mkdir bin && cd bin
        cmake -DCCPP_SUITES=${suites_v16},${suites_v17},${suites_wofs},${suites_rrfs},${suites_old} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} ../src

    - name: Build SCM
      run: |
        cd ${SCM_ROOT}/scm/bin
        make -j4
