name: build_test_and_push_docker

on:
  push:
#    branches:
#      - "main"

env:
  TEST_TAG: mkavulich/ccpp-scm:test
  LATEST_TAG: mkavulich/ccpp-scm:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and export test tag to Docker
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: docker/Dockerfile
#          load: true
#          tags: ${{ env.TEST_TAG }}
#          push: true
      - name: Test
        run: |
          docker pull ${{ env.TEST_TAG }}
          mkdir $HOME/output
          chmod a+rw $HOME/output
          ls -al $HOME/output
          docker run --rm -v $HOME/output:/home ${{ env.TEST_TAG }} ./run_scm.py -c twpice -d
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
